import type { DocumentBlock } from "@/lib/document-blocks";

// Auto-generated from the seeded variant templates in the Budi Setiawan
// workspace. Block ids are stripped; seedDefaultTemplates() regenerates them
// with crypto.randomUUID() so no two templates share a block id.

export type ProposalVariantTemplate = {
  name: string;
  body: string;
  contentBlocks: DocumentBlock[];
  defaultCurrency: string;
  defaultTaxRate: string;
  defaultDownPaymentPercent: string;
  lineItems: string | null;
};

export type ContractVariantTemplate = {
  name: string;
  body: string;
  contentBlocks: DocumentBlock[];
};

export const PROPOSAL_VARIANT_TEMPLATES: ProposalVariantTemplate[] = [
  {
    name: "Branding & Identity Proposal",
    body: "# Branding & Identity Proposal\n\n{{workspace_name}}\n\nPrepared for {{client_name}}\n\n{{today}}\n\n---\n\n## Executive Summary\n\nWe will develop a complete brand identity for {{client_name}} — from strategy through visual system — so your brand is memorable, consistent, and ready to launch.\n\n## Phase 1 — Discovery & Research\n\n- Stakeholder interviews & brand audit\n\n- Competitor & market analysis\n\n- Audience and positioning research\n\n## Phase 2 — Brand Strategy\n\n- Brand positioning & messaging\n\n- Voice and tone guidelines\n\n- Brand personality & value proposition\n\n## Phase 3 — Visual Identity\n\n- Logo design (primary, secondary, mark)\n\n- Color palette & typography system\n\n- Brand guidelines document\n\n## Deliverables\n\n- Logo suite (AI, SVG, PNG)\n\n- Full brand guidelines PDF\n\n- Business card & letterhead templates\n\n- Social media profile kit\n\n## Timeline\n\nEstimated 4 weeks: Discovery (1 wk), Strategy (1 wk), Visual Identity (2 wks). Two revision rounds are included per phase.\n\n## Investment\n\nTotal project investment as set out in the pricing table. A 50% deposit is due to begin; the remainder is due on final delivery.\n\n## Terms & Conditions\n\nThis proposal is valid until {{valid_until}}. Additional revision rounds beyond the included scope will be quoted separately.\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Branding & Identity Proposal"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Prepared for {{client_name}}"},{"type":"text","align":"center","content":"{{today}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Executive Summary"},{"type":"text","content":"We will develop a complete brand identity for {{client_name}} — from strategy through visual system — so your brand is memorable, consistent, and ready to launch."},{"type":"heading","level":2,"content":"Phase 1 — Discovery & Research"},{"type":"list","items":["Stakeholder interviews & brand audit","Competitor & market analysis","Audience and positioning research"],"ordered":false},{"type":"heading","level":2,"content":"Phase 2 — Brand Strategy"},{"type":"list","items":["Brand positioning & messaging","Voice and tone guidelines","Brand personality & value proposition"],"ordered":false},{"type":"heading","level":2,"content":"Phase 3 — Visual Identity"},{"type":"list","items":["Logo design (primary, secondary, mark)","Color palette & typography system","Brand guidelines document"],"ordered":false},{"type":"heading","level":2,"content":"Deliverables"},{"type":"list","items":["Logo suite (AI, SVG, PNG)","Full brand guidelines PDF","Business card & letterhead templates","Social media profile kit"],"ordered":false},{"type":"heading","level":2,"content":"Timeline"},{"type":"text","content":"Estimated 4 weeks: Discovery (1 wk), Strategy (1 wk), Visual Identity (2 wks). Two revision rounds are included per phase."},{"type":"heading","level":2,"content":"Investment"},{"type":"text","content":"Total project investment as set out in the pricing table. A 50% deposit is due to begin; the remainder is due on final delivery."},{"type":"heading","level":2,"content":"Terms & Conditions"},{"type":"text","content":"This proposal is valid until {{valid_until}}. Additional revision rounds beyond the included scope will be quoted separately."}] as DocumentBlock[],
    defaultCurrency: "IDR",
    defaultTaxRate: "0.00",
    defaultDownPaymentPercent: "50.00",
    lineItems: null,
  },
  {
    name: "Consulting & Strategy Proposal",
    body: "# Consulting & Strategy Proposal\n\n{{workspace_name}}\n\nPrepared for {{client_name}}\n\n{{today}}\n\n---\n\n## Executive Summary\n\nThis engagement provides {{client_name}} with focused strategic guidance to solve a defined business challenge and build a clear, actionable roadmap.\n\n## Our Methodology\n\n- Assess — review current state, data, and goals\n\n- Diagnose — identify root causes and opportunities\n\n- Recommend — define priorities and quick wins\n\n- Enable — support execution and change management\n\n## Scope of Engagement\n\n- Kickoff & discovery workshop\n\n- Stakeholder interviews\n\n- Market / internal analysis\n\n- Strategic recommendations & roadmap\n\n- Executive presentation & handoff\n\n## Sessions & Schedule\n\nThe engagement runs over 4 weeks with weekly working sessions plus async support between sessions.\n\n## Deliverables\n\n- Discovery findings summary\n\n- Prioritized strategy roadmap\n\n- Action plan with owners and timelines\n\n## Investment\n\nEngagement fee as set out in the pricing table — either a fixed package or hourly rate. Travel and out-of-pocket expenses are billed at cost.\n\n## Terms & Conditions\n\nThis proposal is valid until {{valid_until}}. Additional sessions or work beyond the defined scope will be quoted separately.\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Consulting & Strategy Proposal"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Prepared for {{client_name}}"},{"type":"text","align":"center","content":"{{today}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Executive Summary"},{"type":"text","content":"This engagement provides {{client_name}} with focused strategic guidance to solve a defined business challenge and build a clear, actionable roadmap."},{"type":"heading","level":2,"content":"Our Methodology"},{"type":"list","items":["Assess — review current state, data, and goals","Diagnose — identify root causes and opportunities","Recommend — define priorities and quick wins","Enable — support execution and change management"],"ordered":false},{"type":"heading","level":2,"content":"Scope of Engagement"},{"type":"list","items":["Kickoff & discovery workshop","Stakeholder interviews","Market / internal analysis","Strategic recommendations & roadmap","Executive presentation & handoff"],"ordered":false},{"type":"heading","level":2,"content":"Sessions & Schedule"},{"type":"text","content":"The engagement runs over 4 weeks with weekly working sessions plus async support between sessions."},{"type":"heading","level":2,"content":"Deliverables"},{"type":"list","items":["Discovery findings summary","Prioritized strategy roadmap","Action plan with owners and timelines"],"ordered":false},{"type":"heading","level":2,"content":"Investment"},{"type":"text","content":"Engagement fee as set out in the pricing table — either a fixed package or hourly rate. Travel and out-of-pocket expenses are billed at cost."},{"type":"heading","level":2,"content":"Terms & Conditions"},{"type":"text","content":"This proposal is valid until {{valid_until}}. Additional sessions or work beyond the defined scope will be quoted separately."}] as DocumentBlock[],
    defaultCurrency: "IDR",
    defaultTaxRate: "0.00",
    defaultDownPaymentPercent: "50.00",
    lineItems: null,
  },
  {
    name: "Mobile App Development Proposal",
    body: "# Mobile App Development Proposal\n\n{{workspace_name}}\n\nPrepared for {{client_name}}\n\n{{today}}\n\n---\n\n## Executive Summary\n\nWe will design and build a mobile application for {{client_name}} — from product definition through a polished MVP — using a modern, scalable tech stack.\n\n## Problem\n\n{{client_name}} needs a mobile experience that delivers its core value to users quickly, with a clean interface and reliable performance.\n\n## Solution & Key Features\n\n- User onboarding & authentication\n\n- Core feature set (to be finalized in discovery)\n\n- Push notifications\n\n- Analytics & crash reporting\n\n## Technical Approach\n\n- Cross-platform (iOS + Android) via a single codebase\n\n- Cloud backend with secure API\n\n- CI/CD pipeline for fast, safe releases\n\n## MVP Scope\n\nWe focus on the highest-impact features first to launch a working MVP, then iterate based on real user feedback.\n\n## Timeline\n\nEstimated 10–12 weeks in two-week sprints: Discovery & design (2 wks), MVP build (6 wks), QA & launch (2 wks).\n\n## Investment\n\nProject investment as set out in the pricing table. Billing follows milestone completion across the build phase.\n\n## Support & Warranty\n\nIncludes 30 days of post-launch bug fixes. Ongoing maintenance and feature work are available under a separate agreement.\n\n## Terms & Conditions\n\nThis proposal is valid until {{valid_until}}. Scope changes outside the defined MVP will be quoted separately.\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Mobile App Development Proposal"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Prepared for {{client_name}}"},{"type":"text","align":"center","content":"{{today}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Executive Summary"},{"type":"text","content":"We will design and build a mobile application for {{client_name}} — from product definition through a polished MVP — using a modern, scalable tech stack."},{"type":"heading","level":2,"content":"Problem"},{"type":"text","content":"{{client_name}} needs a mobile experience that delivers its core value to users quickly, with a clean interface and reliable performance."},{"type":"heading","level":2,"content":"Solution & Key Features"},{"type":"list","items":["User onboarding & authentication","Core feature set (to be finalized in discovery)","Push notifications","Analytics & crash reporting"],"ordered":false},{"type":"heading","level":2,"content":"Technical Approach"},{"type":"list","items":["Cross-platform (iOS + Android) via a single codebase","Cloud backend with secure API","CI/CD pipeline for fast, safe releases"],"ordered":false},{"type":"heading","level":2,"content":"MVP Scope"},{"type":"text","content":"We focus on the highest-impact features first to launch a working MVP, then iterate based on real user feedback."},{"type":"heading","level":2,"content":"Timeline"},{"type":"text","content":"Estimated 10–12 weeks in two-week sprints: Discovery & design (2 wks), MVP build (6 wks), QA & launch (2 wks)."},{"type":"heading","level":2,"content":"Investment"},{"type":"text","content":"Project investment as set out in the pricing table. Billing follows milestone completion across the build phase."},{"type":"heading","level":2,"content":"Support & Warranty"},{"type":"text","content":"Includes 30 days of post-launch bug fixes. Ongoing maintenance and feature work are available under a separate agreement."},{"type":"heading","level":2,"content":"Terms & Conditions"},{"type":"text","content":"This proposal is valid until {{valid_until}}. Scope changes outside the defined MVP will be quoted separately."}] as DocumentBlock[],
    defaultCurrency: "IDR",
    defaultTaxRate: "0.00",
    defaultDownPaymentPercent: "50.00",
    lineItems: null,
  },
  {
    name: "Social Media Marketing Proposal",
    body: "# Social Media Marketing Proposal\n\n{{workspace_name}}\n\nPrepared for {{client_name}}\n\n{{today}}\n\n---\n\n## Executive Summary\n\nWe will manage {{client_name}}'s social media presence end-to-end — strategy, content creation, publishing, community management, and reporting — to grow your audience and drive measurable engagement.\n\n## Objectives\n\n- Increase brand awareness and follower growth\n\n- Drive consistent engagement and reach\n\n- Generate qualified leads from social channels\n\n- Build a consistent, on-brand content presence\n\n## Strategy & Approach\n\nWe start with an audit of your current channels, competitors, and audience. From there we define a content strategy, posting cadence, and platform mix tailored to your goals.\n\n## Content & Platform Plan\n\n- Platform strategy (Instagram, LinkedIn, TikTok, X)\n\n- Monthly content calendar with 12–16 posts\n\n- Copywriting + visual design for each post\n\n- Hashtag and SEO-optimized captions\n\n## Monthly Deliverables\n\n- 12–16 designed posts per month\n\n- Daily community management & engagement\n\n- Monthly performance report with KPIs\n\n- 1 strategy/optimization call per month\n\n## Timeline\n\nOngoing monthly engagement. Onboarding and channel setup are completed within the first 2 weeks; full content cadence begins in month one.\n\n## Investment\n\nMonthly retainer as set out in the pricing table below. This is a rolling engagement with 30 days notice to cancel.\n\n## Reporting & KPIs\n\nWe track reach, engagement rate, follower growth, and lead conversion. A detailed report is delivered at the end of each month.\n\n## Terms & Conditions\n\nThis proposal is valid until {{valid_until}}. Work outside the defined scope will be quoted separately.\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Social Media Marketing Proposal"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Prepared for {{client_name}}"},{"type":"text","align":"center","content":"{{today}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Executive Summary"},{"type":"text","content":"We will manage {{client_name}}'s social media presence end-to-end — strategy, content creation, publishing, community management, and reporting — to grow your audience and drive measurable engagement."},{"type":"heading","level":2,"content":"Objectives"},{"type":"list","items":["Increase brand awareness and follower growth","Drive consistent engagement and reach","Generate qualified leads from social channels","Build a consistent, on-brand content presence"],"ordered":false},{"type":"heading","level":2,"content":"Strategy & Approach"},{"type":"text","content":"We start with an audit of your current channels, competitors, and audience. From there we define a content strategy, posting cadence, and platform mix tailored to your goals."},{"type":"heading","level":2,"content":"Content & Platform Plan"},{"type":"list","items":["Platform strategy (Instagram, LinkedIn, TikTok, X)","Monthly content calendar with 12–16 posts","Copywriting + visual design for each post","Hashtag and SEO-optimized captions"],"ordered":false},{"type":"heading","level":2,"content":"Monthly Deliverables"},{"type":"list","items":["12–16 designed posts per month","Daily community management & engagement","Monthly performance report with KPIs","1 strategy/optimization call per month"],"ordered":false},{"type":"heading","level":2,"content":"Timeline"},{"type":"text","content":"Ongoing monthly engagement. Onboarding and channel setup are completed within the first 2 weeks; full content cadence begins in month one."},{"type":"heading","level":2,"content":"Investment"},{"type":"text","content":"Monthly retainer as set out in the pricing table below. This is a rolling engagement with 30 days notice to cancel."},{"type":"heading","level":2,"content":"Reporting & KPIs"},{"type":"text","content":"We track reach, engagement rate, follower growth, and lead conversion. A detailed report is delivered at the end of each month."},{"type":"heading","level":2,"content":"Terms & Conditions"},{"type":"text","content":"This proposal is valid until {{valid_until}}. Work outside the defined scope will be quoted separately."}] as DocumentBlock[],
    defaultCurrency: "IDR",
    defaultTaxRate: "0.00",
    defaultDownPaymentPercent: "50.00",
    lineItems: null,
  },
];

export const CONTRACT_VARIANT_TEMPLATES: ContractVariantTemplate[] = [
  {
    name: "Consulting Agreement",
    body: "# Consulting Agreement\n\n{{workspace_name}}\n\nContract No. {{contract_number}}\n\n{{contract_date}}\n\n---\n\n## Parties\n\nThis Consulting Agreement (the “Agreement”) is entered into on {{contract_date}} between {{workspace_name}} (“Consultant”) and {{client_name}} (“Client”).\n\n## Services\n\nThe Consultant agrees to provide the consulting services described in the attached scope of work, and any additional services the Parties agree to in writing.\n\n## Compensation\n\nThe Client agrees to pay the Consultant the fees set out in the pricing schedule. Invoices are payable within 14 days of receipt. Reasonable pre-approved expenses will be reimbursed at cost.\n\n## Independent Contractor\n\nThe Consultant is an independent contractor, not an employee. The Consultant is responsible for its own taxes, benefits, and insurance, and has no authority to bind the Client.\n\n## Confidentiality\n\nEach Party agrees to keep confidential any non-public information received from the other Party during the engagement.\n\n## Intellectual Property\n\nUpon full payment, deliverables produced specifically for the Client are assigned to the Client. The Consultant retains ownership of pre-existing materials and know-how.\n\n## Non-Solicitation\n\nDuring the engagement and for 12 months after, neither Party will solicit the other's employees or contractors who were materially involved in the work.\n\n## Term & Termination\n\nThis Agreement begins on {{contract_date}} and continues until {{valid_until}}. Either Party may terminate with 14 days written notice.\n\n## Liability\n\nThe Consultant's total liability under this Agreement shall not exceed the total fees paid by the Client.\n\n## Signatures\n\n___\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Consulting Agreement"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Contract No. {{contract_number}}"},{"type":"text","align":"center","content":"{{contract_date}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Parties"},{"type":"text","content":"This Consulting Agreement (the “Agreement”) is entered into on {{contract_date}} between {{workspace_name}} (“Consultant”) and {{client_name}} (“Client”)."},{"type":"heading","level":2,"content":"Services"},{"type":"text","content":"The Consultant agrees to provide the consulting services described in the attached scope of work, and any additional services the Parties agree to in writing."},{"type":"heading","level":2,"content":"Compensation"},{"type":"text","content":"The Client agrees to pay the Consultant the fees set out in the pricing schedule. Invoices are payable within 14 days of receipt. Reasonable pre-approved expenses will be reimbursed at cost."},{"type":"heading","level":2,"content":"Independent Contractor"},{"type":"text","content":"The Consultant is an independent contractor, not an employee. The Consultant is responsible for its own taxes, benefits, and insurance, and has no authority to bind the Client."},{"type":"heading","level":2,"content":"Confidentiality"},{"type":"text","content":"Each Party agrees to keep confidential any non-public information received from the other Party during the engagement."},{"type":"heading","level":2,"content":"Intellectual Property"},{"type":"text","content":"Upon full payment, deliverables produced specifically for the Client are assigned to the Client. The Consultant retains ownership of pre-existing materials and know-how."},{"type":"heading","level":2,"content":"Non-Solicitation"},{"type":"text","content":"During the engagement and for 12 months after, neither Party will solicit the other's employees or contractors who were materially involved in the work."},{"type":"heading","level":2,"content":"Term & Termination"},{"type":"text","content":"This Agreement begins on {{contract_date}} and continues until {{valid_until}}. Either Party may terminate with 14 days written notice."},{"type":"heading","level":2,"content":"Liability"},{"type":"text","content":"The Consultant's total liability under this Agreement shall not exceed the total fees paid by the Client."},{"type":"heading","level":2,"content":"Signatures"},{"type":"signature"}] as DocumentBlock[],
  },
  {
    name: "Independent Contractor Agreement",
    body: "# Independent Contractor Agreement\n\n{{workspace_name}}\n\nContract No. {{contract_number}}\n\n{{contract_date}}\n\n---\n\n## Parties\n\nThis Independent Contractor Agreement (the “Agreement”) is entered into on {{contract_date}} between {{workspace_name}} (“Contractor”) and {{client_name}} (“Client”).\n\n## Scope of Work\n\nThe Contractor agrees to perform the work described in the attached scope of work, with the skill and care expected of a professional.\n\n## Compensation\n\nThe Client agrees to pay the Contractor the fees set out in the pricing schedule. The Contractor will invoice on completion of milestones, and invoices are payable within 14 days.\n\n## Independent Contractor Status\n\nThe Contractor is engaged as an independent contractor. The Contractor controls how the work is performed and is responsible for its own taxes, benefits, and insurance.\n\n## Equipment & Expenses\n\nThe Contractor provides its own equipment and tools. Reimbursable expenses must be pre-approved in writing by the Client.\n\n## Intellectual Property\n\nUpon full payment, the Contractor assigns to the Client all rights to the work product created under this Agreement.\n\n## Confidentiality\n\nThe Contractor agrees to keep confidential any non-public information received from the Client.\n\n## Term & Termination\n\nThis Agreement begins on {{contract_date}} and continues until {{valid_until}}. Either Party may terminate with 14 days written notice, with the Contractor entitled to payment for completed work.\n\n## Signatures\n\n___\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Independent Contractor Agreement"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Contract No. {{contract_number}}"},{"type":"text","align":"center","content":"{{contract_date}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Parties"},{"type":"text","content":"This Independent Contractor Agreement (the “Agreement”) is entered into on {{contract_date}} between {{workspace_name}} (“Contractor”) and {{client_name}} (“Client”)."},{"type":"heading","level":2,"content":"Scope of Work"},{"type":"text","content":"The Contractor agrees to perform the work described in the attached scope of work, with the skill and care expected of a professional."},{"type":"heading","level":2,"content":"Compensation"},{"type":"text","content":"The Client agrees to pay the Contractor the fees set out in the pricing schedule. The Contractor will invoice on completion of milestones, and invoices are payable within 14 days."},{"type":"heading","level":2,"content":"Independent Contractor Status"},{"type":"text","content":"The Contractor is engaged as an independent contractor. The Contractor controls how the work is performed and is responsible for its own taxes, benefits, and insurance."},{"type":"heading","level":2,"content":"Equipment & Expenses"},{"type":"text","content":"The Contractor provides its own equipment and tools. Reimbursable expenses must be pre-approved in writing by the Client."},{"type":"heading","level":2,"content":"Intellectual Property"},{"type":"text","content":"Upon full payment, the Contractor assigns to the Client all rights to the work product created under this Agreement."},{"type":"heading","level":2,"content":"Confidentiality"},{"type":"text","content":"The Contractor agrees to keep confidential any non-public information received from the Client."},{"type":"heading","level":2,"content":"Term & Termination"},{"type":"text","content":"This Agreement begins on {{contract_date}} and continues until {{valid_until}}. Either Party may terminate with 14 days written notice, with the Contractor entitled to payment for completed work."},{"type":"heading","level":2,"content":"Signatures"},{"type":"signature"}] as DocumentBlock[],
  },
  {
    name: "Non-Disclosure Agreement",
    body: "# Non-Disclosure Agreement\n\n{{workspace_name}}\n\nContract No. {{contract_number}}\n\n{{contract_date}}\n\n---\n\n## Parties\n\nThis Non-Disclosure Agreement (the “Agreement”) is entered into on {{contract_date}} between {{workspace_name}} (“Disclosing Party”) and {{client_name}} (“Receiving Party”).\n\n## Purpose\n\nThe Parties wish to explore a potential business relationship and, in doing so, may exchange confidential information. This Agreement protects that information.\n\n## Definition of Confidential Information\n\n“Confidential Information” means any non-public information disclosed by either Party, whether written or oral, including business plans, technical data, financial information, client lists, and trade secrets.\n\n## Obligations\n\n- Use Confidential Information solely for the Purpose\n\n- Not disclose Confidential Information to third parties\n\n- Protect Confidential Information with reasonable care\n\n- Limit access to personnel who need it\n\n## Exclusions\n\nConfidential Information does not include information that is: already public, independently developed, rightfully received from a third party, or required to be disclosed by law.\n\n## Term\n\nThis Agreement begins on {{contract_date}} and remains in effect for 2 years, or until {{valid_until}}, whichever is later.\n\n## Return of Materials\n\nUpon written request or termination, the Receiving Party must return or destroy all Confidential Information in its possession.\n\n## Remedies\n\nThe Parties acknowledge that a breach may cause irreparable harm and that injunctive relief is an appropriate remedy in addition to other legal remedies.\n\n## General Provisions\n\nThis Agreement constitutes the entire agreement between the Parties regarding confidentiality. It is governed by the laws of the Disclosing Party's jurisdiction.\n\n## Signatures\n\n___\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Non-Disclosure Agreement"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Contract No. {{contract_number}}"},{"type":"text","align":"center","content":"{{contract_date}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Parties"},{"type":"text","content":"This Non-Disclosure Agreement (the “Agreement”) is entered into on {{contract_date}} between {{workspace_name}} (“Disclosing Party”) and {{client_name}} (“Receiving Party”)."},{"type":"heading","level":2,"content":"Purpose"},{"type":"text","content":"The Parties wish to explore a potential business relationship and, in doing so, may exchange confidential information. This Agreement protects that information."},{"type":"heading","level":2,"content":"Definition of Confidential Information"},{"type":"text","content":"“Confidential Information” means any non-public information disclosed by either Party, whether written or oral, including business plans, technical data, financial information, client lists, and trade secrets."},{"type":"heading","level":2,"content":"Obligations"},{"type":"list","items":["Use Confidential Information solely for the Purpose","Not disclose Confidential Information to third parties","Protect Confidential Information with reasonable care","Limit access to personnel who need it"],"ordered":false},{"type":"heading","level":2,"content":"Exclusions"},{"type":"text","content":"Confidential Information does not include information that is: already public, independently developed, rightfully received from a third party, or required to be disclosed by law."},{"type":"heading","level":2,"content":"Term"},{"type":"text","content":"This Agreement begins on {{contract_date}} and remains in effect for 2 years, or until {{valid_until}}, whichever is later."},{"type":"heading","level":2,"content":"Return of Materials"},{"type":"text","content":"Upon written request or termination, the Receiving Party must return or destroy all Confidential Information in its possession."},{"type":"heading","level":2,"content":"Remedies"},{"type":"text","content":"The Parties acknowledge that a breach may cause irreparable harm and that injunctive relief is an appropriate remedy in addition to other legal remedies."},{"type":"heading","level":2,"content":"General Provisions"},{"type":"text","content":"This Agreement constitutes the entire agreement between the Parties regarding confidentiality. It is governed by the laws of the Disclosing Party's jurisdiction."},{"type":"heading","level":2,"content":"Signatures"},{"type":"signature"}] as DocumentBlock[],
  },
  {
    name: "Service Level Agreement",
    body: "# Service Level Agreement\n\n{{workspace_name}}\n\nContract No. {{contract_number}}\n\n{{contract_date}}\n\n---\n\n## Parties\n\nThis Service Level Agreement (the “SLA”) is entered into on {{contract_date}} between {{workspace_name}} (“Provider”) and {{client_name}} (“Client”), and sets out the service levels for the services described below.\n\n## Services Covered\n\n- Hosting, monitoring, and maintenance of the Client's services\n\n- Helpdesk and technical support\n\n- Scheduled backups and security updates\n\n## Service Levels\n\n- 99.5% monthly uptime target\n\n- Response time: critical issues within 4 business hours\n\n- Resolution time: critical issues within 24 hours\n\n- Scheduled maintenance with 48 hours notice\n\n## Support Hours\n\nStandard support is available during business hours, Monday–Friday. Critical incident support is available 24/7.\n\n## Service Credits\n\nIf the Provider fails to meet the uptime target in a given month, the Client is entitled to a service credit as set out in the pricing schedule.\n\n## Exclusions\n\nService levels do not apply to downtime caused by the Client, third-party services, force majeure events, or scheduled maintenance.\n\n## Reporting\n\nThe Provider will deliver a monthly service report covering uptime, incidents, and response metrics.\n\n## Term\n\nThis SLA begins on {{contract_date}} and remains in effect until {{valid_until}}, unless renewed in writing.\n\n## Signatures\n\n___\n",
    contentBlocks: [{"type":"heading","align":"center","level":1,"content":"Service Level Agreement"},{"type":"text","align":"center","content":"{{workspace_name}}"},{"type":"text","align":"center","content":"Contract No. {{contract_number}}"},{"type":"text","align":"center","content":"{{contract_date}}"},{"type":"divider"},{"type":"heading","level":2,"content":"Parties"},{"type":"text","content":"This Service Level Agreement (the “SLA”) is entered into on {{contract_date}} between {{workspace_name}} (“Provider”) and {{client_name}} (“Client”), and sets out the service levels for the services described below."},{"type":"heading","level":2,"content":"Services Covered"},{"type":"list","items":["Hosting, monitoring, and maintenance of the Client's services","Helpdesk and technical support","Scheduled backups and security updates"],"ordered":false},{"type":"heading","level":2,"content":"Service Levels"},{"type":"list","items":["99.5% monthly uptime target","Response time: critical issues within 4 business hours","Resolution time: critical issues within 24 hours","Scheduled maintenance with 48 hours notice"],"ordered":false},{"type":"heading","level":2,"content":"Support Hours"},{"type":"text","content":"Standard support is available during business hours, Monday–Friday. Critical incident support is available 24/7."},{"type":"heading","level":2,"content":"Service Credits"},{"type":"text","content":"If the Provider fails to meet the uptime target in a given month, the Client is entitled to a service credit as set out in the pricing schedule."},{"type":"heading","level":2,"content":"Exclusions"},{"type":"text","content":"Service levels do not apply to downtime caused by the Client, third-party services, force majeure events, or scheduled maintenance."},{"type":"heading","level":2,"content":"Reporting"},{"type":"text","content":"The Provider will deliver a monthly service report covering uptime, incidents, and response metrics."},{"type":"heading","level":2,"content":"Term"},{"type":"text","content":"This SLA begins on {{contract_date}} and remains in effect until {{valid_until}}, unless renewed in writing."},{"type":"heading","level":2,"content":"Signatures"},{"type":"signature"}] as DocumentBlock[],
  },
];
