import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatMoney } from "@/lib/utils";
import { CheckCircle2, Clock3, Landmark, Wallet } from "lucide-react";

export function ProjectOverview({ project, progress, trackedMinutes, billableAmount, invoicedAmount, outstandingAmount, retainerPeriod, recentTime, recentInvoices, recentFiles, editAction, billingEditAction, locale, t }: any) {
  const isRetainer = project.billingModel === "retainer";
  const isHourly = project.billingModel === "hourly" || project.billingType === "hours";
  const billingLabel = isRetainer ? "Retainer" : isHourly ? t("Per Jam", "Hourly") : t("Harga Tetap", "Fixed Price");
  const configuredAmount = Number(isRetainer ? project.retainerFee : isHourly ? project.rate : project.budget) || 0;
  const kpiLabel = isRetainer ? t("Nilai Retainer", "Retainer Value") : isHourly ? t("Nilai Tagihan", "Billable Amount") : t("Nilai Proyek", "Project Value");
  const taskProgress = progress.total ? `${progress.done}/${progress.total} · ${progress.percent}%` : t("Belum ada tugas", "No tasks yet");
  const invoicePercent = configuredAmount > 0 ? Math.min(100, Math.round((invoicedAmount / configuredAmount) * 100)) : 0;
  const includedMinutes = Number(retainerPeriod?.includedMinutesSnapshot ?? project.retainerIncludedMinutes ?? 0);
  const usedMinutes = Number(retainerPeriod?.approvedMinutes ?? 0);
  const usagePercent = includedMinutes > 0 ? Math.min(100, Math.round((usedMinutes / includedMinutes) * 100)) : 0;
  const progressTitle = isRetainer ? t("Pemakaian Retainer", "Retainer Usage") : t("Progres Invoice", "Invoice Progress");
  const progressPercent = isRetainer ? usagePercent : invoicePercent;
  const progressLead = isRetainer ? `${Math.round(usedMinutes / 60)}h / ${Math.round(includedMinutes / 60)}h` : `${formatMoney(invoicedAmount, project.currency)} / ${formatMoney(configuredAmount, project.currency)}`;
  const progressRest = isRetainer ? `${Math.max(0, Math.round((includedMinutes - usedMinutes) / 60))}h ${t("tersisa", "left")}` : `${formatMoney(Math.max(0, configuredAmount - invoicedAmount), project.currency)} ${t("tersisa", "left")}`;
  const kpis = [[t("Jam Tercatat", "Tracked Hours"), `${Math.floor(trackedMinutes / 60)}h ${trackedMinutes % 60}m`, Clock3], [t("Progres Tugas", "Task Progress"), taskProgress, CheckCircle2], [kpiLabel, formatMoney(billableAmount, project.currency), Landmark], [t("Belum Dibayar", "Outstanding"), formatMoney(outstandingAmount, project.currency), Wallet]] as const;
  const section = (title: string, items: any[], href: string, render: (item: any) => React.ReactNode) => <Card className="h-full rounded-xl"><CardContent className="flex h-full min-h-56 flex-col p-4"><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-bold">{title}</h3><Link href={href} className="text-xs font-medium text-primary hover:underline">{t("Lihat semua", "View all")}</Link></div><div className="divide-y">{items.length ? items.map(render) : <p className="py-8 text-center text-sm text-muted-foreground">{t("Belum ada data", "No data yet")}</p>}</div></CardContent></Card>;
  return <div className="space-y-4">
    <div className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2 lg:grid-cols-4">{kpis.map(([label,value,Icon], index)=><div key={label} className={`flex items-center gap-3 p-4 ${index ? "border-t sm:border-l sm:border-t-0" : ""} ${index === 2 ? "sm:border-l-0 sm:border-t lg:border-l lg:border-t-0" : ""}`}><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div><div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="truncate text-lg font-bold tabular-nums">{value}</p></div></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-3">
      <Card className="h-full rounded-xl"><CardContent className="flex h-full flex-col p-4"><h3 className="mb-4 text-sm font-bold">{t("Detail Proyek", "Project Details")}</h3><dl className="space-y-3 text-sm"><div><dt className="text-xs text-muted-foreground">Client</dt><dd className="font-medium">{project.clientName || t("Tanpa klien", "No client")}</dd></div><div><dt className="text-xs text-muted-foreground">{t("Dibuat", "Created")}</dt><dd>{new Date(project.createdAt).toLocaleDateString(locale)}</dd></div><div><dt className="text-xs text-muted-foreground">{t("Jatuh tempo", "Due date")}</dt><dd>{project.dueDate ? new Date(project.dueDate).toLocaleDateString(locale) : "—"}</dd></div><div><dt className="text-xs text-muted-foreground">Status</dt><dd><Badge variant="outline">{project.status}</Badge></dd></div><div><dt className="text-xs text-muted-foreground">{t("Deskripsi", "Description")}</dt><dd>{project.description || t("Tidak ada deskripsi", "No description")}</dd></div></dl><div className="mt-auto border-t pt-3">{editAction}</div></CardContent></Card>
      <Card className="h-full rounded-xl"><CardContent className="flex h-full flex-col p-4"><h3 className="mb-4 text-sm font-bold">{t("Pengaturan Billing", "Billing Settings")}</h3><dl className="space-y-3 text-sm"><div><dt className="text-xs text-muted-foreground">{t("Model billing", "Billing model")}</dt><dd className="font-medium">{billingLabel}</dd></div><div><dt className="text-xs text-muted-foreground">{isRetainer ? t("Biaya bulanan", "Monthly fee") : isHourly ? t("Tarif per jam", "Hourly rate") : t("Nilai proyek", "Project value")}</dt><dd className="font-mono font-bold">{configuredAmount ? `${formatMoney(configuredAmount, project.currency)}${isHourly ? `/${t("jam", "hr")}` : ""}` : t("Belum diatur", "Not set")}</dd></div><div><dt className="text-xs text-muted-foreground">Currency</dt><dd>{project.currency}</dd></div>{isRetainer && <div><dt className="text-xs text-muted-foreground">{t("Jam termasuk", "Included hours")}</dt><dd>{Math.round(Number(project.retainerIncludedMinutes || 0) / 60)}h</dd></div>}</dl><div className="mt-auto border-t pt-3">{billingEditAction}</div></CardContent></Card>
      <Card className="h-full rounded-xl"><CardContent className="flex h-full flex-col p-4"><h3 className="mb-4 text-sm font-bold">{progressTitle}</h3><p className="font-mono text-xl font-bold">{configuredAmount || isRetainer ? progressLead : "—"}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full ${progressPercent >= 90 ? "bg-rose-500" : progressPercent >= 70 ? "bg-amber-500" : "bg-primary"}`} style={{width:`${progressPercent}%`}} /></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{progressPercent}% {isRetainer ? t("terpakai", "used") : t("ditagih", "invoiced")}</span><span>{progressRest}</span></div><div className="mt-auto border-t pt-3"><Link href="?tab=billing" className="text-xs font-medium text-primary hover:underline">{t("Kelola invoice", "Manage invoices")}</Link></div></CardContent></Card>
    </div>
    <div className="grid gap-4 lg:grid-cols-3">
      {section(t("Log Waktu Terbaru", "Recent Time Logs"), recentTime, "?tab=time", (x)=><div key={x.id} className="flex justify-between py-3 text-sm"><span className="truncate">{x.description || x.taskTitle || t("Tanpa judul", "Untitled")}</span><strong className="font-mono">{Math.round(x.durationMinutes || 0)}m</strong></div>)}
      {section(t("Invoice Terbaru", "Recent Invoices"), recentInvoices, "?tab=billing", (x)=><div key={x.id} className="flex justify-between py-3 text-sm"><span>{x.invoiceNumber}</span><strong className="font-mono">{formatMoney(x.total,x.currency)}</strong></div>)}
      {section(t("Berkas Terbaru", "Recent Files"), recentFiles, "?tab=files", (x)=><div key={x.id} className="py-3 text-sm"><span className="truncate">{x.name}</span></div>)}
    </div>
  </div>;
}
