# syntax=docker/dockerfile:1

FROM node:22-alpine AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps --ignore-scripts

FROM deps AS builder
COPY . .
ARG DATABASE_URL
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG R2_ACCOUNT_ID
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_BUCKET_NAME
ARG R2_PUBLIC_ENDPOINT
ARG OPENAI_API_KEY
ARG OPENAI_BASE_URL
ARG OPENAI_COMPATIBLE_BASE_URL
ARG OPENAI_COMPATIBLE_API_KEY
ARG RESEND_API_KEY
ARG MAX_UPLOAD_MB
ARG SIGNED_URL_TTL_SECONDS
ENV DATABASE_URL=$DATABASE_URL
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV R2_ACCOUNT_ID=$R2_ACCOUNT_ID
ENV R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
ENV R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
ENV R2_BUCKET_NAME=$R2_BUCKET_NAME
ENV R2_PUBLIC_ENDPOINT=$R2_PUBLIC_ENDPOINT
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_BASE_URL=$OPENAI_BASE_URL
ENV OPENAI_COMPATIBLE_BASE_URL=$OPENAI_COMPATIBLE_BASE_URL
ENV OPENAI_COMPATIBLE_API_KEY=$OPENAI_COMPATIBLE_API_KEY
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV MAX_UPLOAD_MB=$MAX_UPLOAD_MB
ENV SIGNED_URL_TTL_SECONDS=$SIGNED_URL_TTL_SECONDS
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
