CREATE TABLE upload_intents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  actor_type text NOT NULL,
  actor_id text NOT NULL,
  destination_type text NOT NULL,
  destination_id text NOT NULL,
  idempotency_key text NOT NULL,
  quarantine_key text NOT NULL UNIQUE,
  final_key text NOT NULL UNIQUE,
  expected_mime text NOT NULL,
  expected_bytes bigint NOT NULL,
  max_bytes bigint NOT NULL,
  expected_sha256 text,
  provider_etag text,
  provider_version_id text,
  state text NOT NULL DEFAULT 'reserved',
  version integer NOT NULL DEFAULT 0,
  final_file_id uuid REFERENCES files(id) ON DELETE SET NULL,
  promotion_attempt_id uuid,
  promotion_lease_owner text,
  promotion_lease_expires_at timestamptz,
  retry_count integer NOT NULL DEFAULT 0,
  last_error_code text,
  cleanup_retry_at timestamptz,
  expires_at timestamptz NOT NULL,
  uploaded_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT upload_intents_actor_type_check CHECK (actor_type IN ('user','portal','public')),
  CONSTRAINT upload_intents_state_check CHECK (state IN ('reserved','uploaded','validating','promoting','promotion_failed','completed','aborted','expired','quarantined','failed_cleanup')),
  CONSTRAINT upload_intents_bytes_check CHECK (expected_bytes >= 0 AND max_bytes >= expected_bytes),
  CONSTRAINT upload_intents_sha256_check CHECK (expected_sha256 IS NULL OR expected_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT upload_intents_retry_check CHECK (retry_count BETWEEN 0 AND 10),
  CONSTRAINT upload_intents_actor_idempotency_unique UNIQUE (workspace_id, actor_type, actor_id, destination_type, destination_id, idempotency_key)
);
CREATE INDEX upload_intents_reconcile_idx ON upload_intents(state, expires_at, cleanup_retry_at);

CREATE TABLE upload_quota_reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intent_id uuid NOT NULL UNIQUE REFERENCES upload_intents(id) ON DELETE CASCADE,
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  bytes bigint NOT NULL,
  files integer NOT NULL DEFAULT 1,
  state text NOT NULL DEFAULT 'active',
  version integer NOT NULL DEFAULT 0,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  released_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT upload_quota_reservations_state_check CHECK (state IN ('active','consumed','released')),
  CONSTRAINT upload_quota_reservations_amount_check CHECK (bytes >= 0 AND files = 1)
);
CREATE INDEX upload_quota_reservations_active_idx ON upload_quota_reservations(workspace_id, state, expires_at);
