"use server";

import { sql } from "drizzle-orm";
import { db } from "@/db";
import { requireAdmin } from "@/lib/admin";
import { enforceServerActionRateLimit } from "@/lib/distributed-rate-limit";
import { getRangeWindow, parseGrowthRange, type GrowthRange } from "@/lib/admin-growth-metrics";

export type GrowthDashboard = {
  range: GrowthRange; generatedAt: string;
  signups: number; activated: number; paidAccounts: number; mrr: number; arr: number; arpu: number | null;
  completedPayments: number; activeWorkspaces: number; activeUsers: number; wau: number; mau: number; projects: number; tasks: number; projectsPerActiveUser: number | null; tasksPerProject: number | null; timeTrackingWorkspaces: number; portalWorkspaces: number;
  firstClientCount: number; firstProjectCount: number; firstTaskCount: number; firstInvoiceCount: number; firstPortalCount: number;
  subscriptionStarted: number; subscriptionUpgraded: number; subscriptionRenewed: number; subscriptionExpired: number; subscriptionReactivated: number; freeToPaidRate: number | null; upgradeRate: number | null; monthlyChurnRate: number | null; subscriptionTrackingSince: string | null;
  previous: { signups: number; activated: number; paidAccounts: number; mrr: number };
  unavailable: { visitors: string; referrals: string; cac: string }; visitors: number; signupStarts: number; signupCompletions: number; organic: number; referrals: number; spend: number; cps: number | null; cac: number | null; analytics_events?: string; marketing_spend?: string;
  trends: Array<{ bucket: string; visitors: number; signupStarts: number; signupCompletions: number; activated: number; revenue: number }>;
  acquisition: Array<{ source: string; campaign: string; visitors: number; signupCompletions: number; spend: number; conversionRate: number | null; cac: number | null }>;
  usagePages: Array<{ page: string; views: number; uniqueActors: number; workspaces: number }>;
  usageFeatures: Array<{ feature: string; actions: number; uniqueActors: number; workspaces: number }>;
};

export async function getAdminGrowthDashboard(input?: string): Promise<GrowthDashboard> {
  const admin = await requireAdmin();
  await enforceServerActionRateLimit("admin:growth-kpis", admin.id, { limit: 120, windowSec: 60 });
  const range = parseGrowthRange(input);
  const { days } = getRangeWindow(range);
  const interval = range === "12m" ? sql`make_interval(months => 12)` : sql`make_interval(days => ${days})`;
  const result = await db.execute(sql`
    WITH bounds AS (
      SELECT now() AS finish, now() - ${interval} AS start, now() - (${interval}) * 2 AS previous_start
    ), activation_milestones AS (
      SELECT
        w.id,
        (SELECT min(created_at) FROM clients WHERE workspace_id = w.id) AS first_client_at,
        (SELECT min(created_at) FROM projects WHERE workspace_id = w.id) AS first_project_at,
        (SELECT min(ts) FROM (
          SELECT created_at AS ts FROM tasks WHERE workspace_id = w.id
          UNION ALL SELECT created_at FROM invoices WHERE workspace_id = w.id
          UNION ALL SELECT created_at FROM time_entries WHERE workspace_id = w.id
          UNION ALL SELECT visited_at FROM portal_visits WHERE workspace_id = w.id
        ) activity) AS first_activity_at
      FROM workspaces w
    ), activation_dates AS (
      SELECT id, GREATEST(first_client_at, first_project_at, first_activity_at) AS activated_at
      FROM activation_milestones
      WHERE first_client_at IS NOT NULL AND first_project_at IS NOT NULL AND first_activity_at IS NOT NULL
    ), latest_plan AS (
      SELECT DISTINCT ON (workspace_id) workspace_id, amount, billing_period FROM pakasir_payments WHERE status = 'completed' AND payment_type = 'plan' ORDER BY workspace_id, COALESCE(paid_at, created_at) DESC
    ), paid_now AS (
      SELECT DISTINCT wm.workspace_id, u.plan, u.plan_expires_at, lp.amount, lp.billing_period FROM workspace_members wm JOIN users u ON u.id = wm.user_id LEFT JOIN latest_plan lp ON lp.workspace_id = wm.workspace_id WHERE wm.role = 'owner' AND u.plan <> 'free' AND (u.plan_expires_at IS NULL OR u.plan_expires_at > now())
    ), current_metrics AS (
      SELECT
        (SELECT count(*) FROM users u, bounds b WHERE u.created_at >= b.start AND u.created_at < b.finish)::int AS signups,
        (SELECT count(DISTINCT anonymous_id) FROM analytics_events, bounds WHERE event_name = 'landing_viewed' AND occurred_at >= start AND occurred_at < finish)::int AS visitors,
        (SELECT count(*) FROM analytics_events, bounds WHERE event_name = 'signup_started' AND occurred_at >= start AND occurred_at < finish)::int AS signup_starts,
        (SELECT count(*) FROM analytics_events, bounds WHERE event_name = 'signup_completed' AND occurred_at >= start AND occurred_at < finish)::int AS signup_completions,
        (SELECT count(DISTINCT anonymous_id) FROM analytics_events, bounds WHERE event_name = 'landing_viewed' AND medium = 'organic' AND occurred_at >= start AND occurred_at < finish)::int AS organic,
        (SELECT count(DISTINCT anonymous_id) FROM analytics_events, bounds WHERE event_name = 'landing_viewed' AND referral_id IS NOT NULL AND occurred_at >= start AND occurred_at < finish)::int AS referrals,
        (SELECT COALESCE(sum(amount), 0) FROM marketing_spend, bounds WHERE spend_date >= start::date AND spend_date < finish::date AND currency = 'IDR')::numeric AS spend,
        (SELECT count(*) FROM activation_dates a, bounds b WHERE a.activated_at >= b.start AND a.activated_at < b.finish)::int AS activated,
        (SELECT count(*) FROM paid_now)::int AS paid_accounts,
        (SELECT COALESCE(sum(CASE WHEN billing_period = 'monthly' THEN amount::numeric WHEN billing_period = 'yearly' THEN amount::numeric / 12 ELSE NULL END), NULL) FROM paid_now) AS mrr,
        (SELECT count(*) FROM pakasir_payments p, bounds b WHERE p.status = 'completed' AND p.payment_type = 'plan' AND COALESCE(p.paid_at, p.created_at) >= b.start AND COALESCE(p.paid_at, p.created_at) < b.finish)::int AS completed_payments,
        (SELECT count(DISTINCT workspace_id) FROM (SELECT workspace_id FROM clients WHERE created_at >= (SELECT start FROM bounds) UNION SELECT workspace_id FROM projects WHERE created_at >= (SELECT start FROM bounds) UNION SELECT workspace_id FROM tasks WHERE created_at >= (SELECT start FROM bounds) UNION SELECT workspace_id FROM invoices WHERE created_at >= (SELECT start FROM bounds) UNION SELECT workspace_id FROM time_entries WHERE created_at >= (SELECT start FROM bounds) UNION SELECT workspace_id FROM portal_visits WHERE visited_at >= (SELECT start FROM bounds)) active)::int AS active_workspaces,
        (SELECT count(DISTINCT user_id) FROM (SELECT created_by AS user_id FROM tasks, bounds WHERE created_at >= start AND created_at < finish AND created_by IS NOT NULL UNION SELECT user_id FROM time_entries, bounds WHERE created_at >= start AND created_at < finish UNION SELECT created_by FROM projects, bounds WHERE created_at >= start AND created_at < finish AND created_by IS NOT NULL) actors)::int AS active_users,
        (SELECT count(DISTINCT user_id) FROM (SELECT created_by AS user_id FROM tasks, bounds WHERE created_at >= finish - interval '7 days' AND created_at < finish AND created_by IS NOT NULL UNION SELECT user_id FROM time_entries, bounds WHERE created_at >= finish - interval '7 days' AND created_at < finish UNION SELECT created_by FROM projects, bounds WHERE created_at >= finish - interval '7 days' AND created_at < finish AND created_by IS NOT NULL) actors)::int AS wau,
        (SELECT count(DISTINCT user_id) FROM (SELECT created_by AS user_id FROM tasks, bounds WHERE created_at >= finish - interval '30 days' AND created_at < finish AND created_by IS NOT NULL UNION SELECT user_id FROM time_entries, bounds WHERE created_at >= finish - interval '30 days' AND created_at < finish UNION SELECT created_by FROM projects, bounds WHERE created_at >= finish - interval '30 days' AND created_at < finish AND created_by IS NOT NULL) actors)::int AS mau,
        (SELECT count(*) FROM projects p, bounds b WHERE p.created_at >= b.start AND p.created_at < b.finish)::int AS projects,
        (SELECT count(*) FROM tasks t, bounds b WHERE t.created_at >= b.start AND t.created_at < b.finish)::int AS tasks,
        (SELECT count(*) FROM activation_milestones m, bounds b WHERE m.first_client_at >= b.start AND m.first_client_at < b.finish)::int AS first_client_count,
        (SELECT count(*) FROM activation_milestones m, bounds b WHERE m.first_project_at >= b.start AND m.first_project_at < b.finish)::int AS first_project_count,
        (SELECT count(*) FROM (SELECT workspace_id, min(created_at) AS first_at FROM tasks GROUP BY workspace_id) x, bounds b WHERE x.first_at >= b.start AND x.first_at < b.finish)::int AS first_task_count,
        (SELECT count(*) FROM (SELECT workspace_id, min(created_at) AS first_at FROM invoices GROUP BY workspace_id) x, bounds b WHERE x.first_at >= b.start AND x.first_at < b.finish)::int AS first_invoice_count,
        (SELECT count(*) FROM (SELECT workspace_id, min(visited_at) AS first_at FROM portal_visits GROUP BY workspace_id) x, bounds b WHERE x.first_at >= b.start AND x.first_at < b.finish)::int AS first_portal_count,
        (SELECT count(*) FROM subscription_events s, bounds b WHERE s.event_type = 'started' AND s.occurred_at >= b.start AND s.occurred_at < b.finish)::int AS subscription_started,
        (SELECT count(*) FROM subscription_events s, bounds b WHERE s.event_type = 'upgraded' AND s.occurred_at >= b.start AND s.occurred_at < b.finish)::int AS subscription_upgraded,
        (SELECT count(*) FROM subscription_events s, bounds b WHERE s.event_type = 'renewed' AND s.occurred_at >= b.start AND s.occurred_at < b.finish)::int AS subscription_renewed,
        (SELECT count(*) FROM subscription_events s, bounds b WHERE s.event_type = 'expired' AND s.occurred_at >= b.start AND s.occurred_at < b.finish)::int AS subscription_expired,
        (SELECT count(*) FROM subscription_events s, bounds b WHERE s.event_type = 'reactivated' AND s.occurred_at >= b.start AND s.occurred_at < b.finish)::int AS subscription_reactivated,
        (SELECT min(occurred_at)::text FROM subscription_events) AS subscription_tracking_since,
        (SELECT count(DISTINCT te.workspace_id) FROM time_entries te, bounds b WHERE te.created_at >= b.start AND te.created_at < b.finish)::int AS time_tracking_workspaces,
        (SELECT count(DISTINCT pv.workspace_id) FROM portal_visits pv, bounds b WHERE pv.visited_at >= b.start AND pv.visited_at < b.finish)::int AS portal_workspaces
    ), previous_metrics AS (
      SELECT (SELECT count(*) FROM users u, bounds b WHERE u.created_at >= b.previous_start AND u.created_at < b.start)::int AS signups, (SELECT count(*) FROM activation_dates a, bounds b WHERE a.activated_at >= b.previous_start AND a.activated_at < b.start)::int AS activated, NULL::int AS paid_accounts, NULL::numeric AS mrr
    ) SELECT current_metrics.*, previous_metrics.signups AS previous_signups, previous_metrics.activated AS previous_activated, previous_metrics.paid_accounts AS previous_paid_accounts, previous_metrics.mrr AS previous_mrr, now()::text AS generated_at FROM current_metrics, previous_metrics`);
  const r = result.rows[0] as Record<string, string | number>;
  const bucket = range === "12m" ? sql`'month'` : sql`'day'`;
  const detail = await db.execute(sql`WITH bounds AS (SELECT now() AS finish, now() - ${interval} AS start), buckets AS (SELECT generate_series(date_trunc(${bucket}, (SELECT start FROM bounds)), date_trunc(${bucket}, (SELECT finish FROM bounds) - interval '1 microsecond'), CASE WHEN ${range === "12m"} THEN interval '1 month' ELSE interval '1 day' END) AS bucket), events AS (SELECT date_trunc(${bucket}, occurred_at) AS bucket, count(DISTINCT anonymous_id) FILTER (WHERE event_name='landing_viewed') visitors, count(*) FILTER (WHERE event_name='signup_started') signup_starts, count(*) FILTER (WHERE event_name='signup_completed') signup_completions FROM analytics_events, bounds WHERE occurred_at >= start AND occurred_at < finish GROUP BY 1), milestones AS (SELECT w.id, (SELECT min(created_at) FROM clients WHERE workspace_id=w.id) first_client_at, (SELECT min(created_at) FROM projects WHERE workspace_id=w.id) first_project_at, (SELECT min(ts) FROM (SELECT created_at ts FROM tasks WHERE workspace_id=w.id UNION ALL SELECT created_at FROM invoices WHERE workspace_id=w.id UNION ALL SELECT created_at FROM time_entries WHERE workspace_id=w.id UNION ALL SELECT visited_at FROM portal_visits WHERE workspace_id=w.id) q) first_activity_at FROM workspaces w), activation_dates AS (SELECT id, GREATEST(first_client_at, first_project_at, first_activity_at) activated_at FROM milestones WHERE first_client_at IS NOT NULL AND first_project_at IS NOT NULL AND first_activity_at IS NOT NULL), activations AS (SELECT date_trunc(${bucket}, activated_at) bucket, count(*)::int activated FROM activation_dates, bounds WHERE activated_at >= start AND activated_at < finish GROUP BY 1), revenue AS (SELECT date_trunc(${bucket}, COALESCE(paid_at,created_at)) AS bucket, COALESCE(sum(amount),0) revenue FROM pakasir_payments, bounds WHERE status='completed' AND payment_type='plan' AND COALESCE(paid_at,created_at) >= start AND COALESCE(paid_at,created_at) < finish GROUP BY 1) SELECT b.bucket::text, COALESCE(e.visitors,0)::int visitors, COALESCE(e.signup_starts,0)::int signup_starts, COALESCE(e.signup_completions,0)::int signup_completions, COALESCE(a.activated,0)::int activated, COALESCE(rv.revenue,0)::numeric revenue FROM buckets b LEFT JOIN events e USING(bucket) LEFT JOIN activations a USING(bucket) LEFT JOIN revenue rv USING(bucket) ORDER BY b.bucket`);
  const acquisitionResult = await db.execute(sql`WITH bounds AS (SELECT now() AS finish, now() - ${interval} AS start), a AS (SELECT COALESCE(source, 'direct / unknown') source, COALESCE(campaign, '—') campaign, count(DISTINCT anonymous_id) FILTER (WHERE event_name='landing_viewed') visitors, count(*) FILTER (WHERE event_name='signup_completed') signup_completions FROM analytics_events, bounds WHERE occurred_at >= start AND occurred_at < finish GROUP BY 1,2), s AS (SELECT COALESCE(source, 'direct / unknown') source, COALESCE(campaign, '—') campaign, COALESCE(sum(amount),0) spend FROM marketing_spend, bounds WHERE spend_date >= start::date AND spend_date < finish::date AND currency='IDR' GROUP BY 1,2) SELECT COALESCE(a.source,s.source) source, COALESCE(a.campaign,s.campaign) campaign, COALESCE(a.visitors,0)::int visitors, COALESCE(a.signup_completions,0)::int signup_completions, COALESCE(s.spend,0)::numeric spend FROM a FULL JOIN s USING(source,campaign) ORDER BY signup_completions DESC, spend DESC LIMIT 20`);
  const usagePagesResult = await db.execute(sql`WITH bounds AS (SELECT now() AS finish, now() - ${interval} AS start) SELECT COALESCE(NULLIF(metadata->>'path',''), 'Unknown page') page, count(*)::int views, count(DISTINCT COALESCE(user_id, anonymous_id))::int unique_actors, count(DISTINCT workspace_id)::int workspaces FROM analytics_events, bounds WHERE event_name='page_viewed' AND occurred_at >= start AND occurred_at < finish GROUP BY 1 ORDER BY views DESC LIMIT 20`);
  const usageFeaturesResult = await db.execute(sql`WITH bounds AS (SELECT now() AS finish, now() - ${interval} AS start), events AS (SELECT COALESCE(NULLIF(metadata->>'feature',''), 'Tracked feature') feature, count(*)::int actions, count(DISTINCT COALESCE(user_id, anonymous_id))::int unique_actors, count(DISTINCT workspace_id)::int workspaces FROM analytics_events, bounds WHERE event_name='feature_used' AND occurred_at >= start AND occurred_at < finish GROUP BY 1), operations AS (SELECT 'Projects created' feature, count(*)::int actions, count(DISTINCT created_by)::int unique_actors, count(DISTINCT workspace_id)::int workspaces FROM projects, bounds WHERE created_at >= start AND created_at < finish UNION ALL SELECT 'Tasks created', count(*)::int, count(DISTINCT created_by)::int, count(DISTINCT workspace_id)::int FROM tasks, bounds WHERE created_at >= start AND created_at < finish UNION ALL SELECT 'Invoices created', count(*)::int, 0::int, count(DISTINCT workspace_id)::int FROM invoices, bounds WHERE created_at >= start AND created_at < finish UNION ALL SELECT 'Time entries logged', count(*)::int, count(DISTINCT user_id)::int, count(DISTINCT workspace_id)::int FROM time_entries, bounds WHERE created_at >= start AND created_at < finish UNION ALL SELECT 'Files uploaded', count(*)::int, count(DISTINCT uploaded_by)::int, count(DISTINCT workspace_id)::int FROM files, bounds WHERE created_at >= start AND created_at < finish AND upload_state='completed' UNION ALL SELECT 'Portal visits', count(*)::int, 0::int, count(DISTINCT workspace_id)::int FROM portal_visits, bounds WHERE visited_at >= start AND visited_at < finish UNION ALL SELECT 'Proposals created', count(*)::int, 0::int, count(DISTINCT workspace_id)::int FROM proposals, bounds WHERE created_at >= start AND created_at < finish UNION ALL SELECT 'Contracts created', count(*)::int, 0::int, count(DISTINCT workspace_id)::int FROM contracts, bounds WHERE created_at >= start AND created_at < finish) SELECT feature, actions, unique_actors, workspaces FROM events UNION ALL SELECT feature, actions, unique_actors, workspaces FROM operations ORDER BY actions DESC LIMIT 20`);
  const trends = detail.rows.map((x) => ({ bucket: String(x.bucket), visitors: Number(x.visitors), signupStarts: Number(x.signup_starts), signupCompletions: Number(x.signup_completions), activated: Number(x.activated), revenue: Number(x.revenue) }));
  const acquisition = acquisitionResult.rows.map((x) => { const visitors = Number(x.visitors), completions = Number(x.signup_completions), spend = Number(x.spend); return { source: String(x.source), campaign: String(x.campaign), visitors, signupCompletions: completions, spend, conversionRate: visitors ? completions / visitors * 100 : null, cac: completions ? spend / completions : null }; });
  const mrr = Number(r.mrr ?? 0), paidAccounts = Number(r.paid_accounts ?? 0);
  const n = (key: string) => Number(r[key] ?? 0);
  const started = n("subscription_started"), reactivated = n("subscription_reactivated"), upgraded = n("subscription_upgraded"), expired = n("subscription_expired");
  return { range, generatedAt: String(r.generated_at), signups: n("signups"), activated: n("activated"), paidAccounts, mrr, arr: mrr * 12, arpu: paidAccounts ? mrr / paidAccounts : null, completedPayments: n("completed_payments"), activeWorkspaces: n("active_workspaces"), activeUsers: n("active_users"), wau: n("wau"), mau: n("mau"), projects: n("projects"), tasks: n("tasks"), projectsPerActiveUser: n("active_users") ? n("projects") / n("active_users") : null, tasksPerProject: n("projects") ? n("tasks") / n("projects") : null, timeTrackingWorkspaces: n("time_tracking_workspaces"), portalWorkspaces: n("portal_workspaces"), firstClientCount: n("first_client_count"), firstProjectCount: n("first_project_count"), firstTaskCount: n("first_task_count"), firstInvoiceCount: n("first_invoice_count"), firstPortalCount: n("first_portal_count"), subscriptionStarted: started, subscriptionUpgraded: upgraded, subscriptionRenewed: n("subscription_renewed"), subscriptionExpired: expired, subscriptionReactivated: reactivated, freeToPaidRate: n("signup_completions") ? (started + reactivated) / n("signup_completions") * 100 : null, upgradeRate: started + reactivated + upgraded ? upgraded / (started + reactivated + upgraded) * 100 : null, monthlyChurnRate: null, subscriptionTrackingSince: r.subscription_tracking_since ? String(r.subscription_tracking_since) : null, previous: { signups: n("previous_signups"), activated: n("previous_activated"), paidAccounts: n("previous_paid_accounts"), mrr: n("previous_mrr") }, unavailable: { visitors: "No landing events in selected range", referrals: "No referral events in selected range", cac: "No spend or signup completions in selected range" }, visitors: n("visitors"), signupStarts: n("signup_starts"), signupCompletions: n("signup_completions"), organic: n("organic"), referrals: n("referrals"), spend: n("spend"), cps: n("signup_starts") ? n("spend") / n("signup_starts") : null, cac: n("signup_completions") ? n("spend") / n("signup_completions") : null, analytics_events: "analytics_events", marketing_spend: "marketing_spend", trends, acquisition, usagePages: usagePagesResult.rows.map((x) => ({ page: String(x.page), views: Number(x.views), uniqueActors: Number(x.unique_actors), workspaces: Number(x.workspaces) })), usageFeatures: usageFeaturesResult.rows.map((x) => ({ feature: String(x.feature), actions: Number(x.actions), uniqueActors: Number(x.unique_actors), workspaces: Number(x.workspaces) })) };
}

/** @deprecated Use getAdminGrowthDashboard. */
export async function getAdminKpis() { const d = await getAdminGrowthDashboard("30d"); return { totalUsers: d.activeUsers, newUsers7d: d.signups, newUsers30d: d.signups, totalWorkspaces: d.activeWorkspaces, completedPayments: d.completedPayments, mrr: String(d.mrr), freeToPaidConversion: d.signups ? Math.round((d.paidAccounts / d.signups) * 1000) / 10 : 0, paidUsers: d.paidAccounts }; }

export { parseGrowthRange };
