import { comparePercent, type GrowthRange } from "@/lib/admin-growth-metrics";
import type { GrowthDashboard } from "@/lib/actions/admin/dashboard";

const ranges: GrowthRange[] = ["7d", "30d", "90d", "12m"];
const money = (value: number | null) => value == null ? "—" : new Intl.NumberFormat("id-ID", { maximumFractionDigits: 0 }).format(value);

function Card({ label, value, comparison, help }: { label: string; value: string | number; comparison?: number | null; help: string }) {
  return <div className="rounded-xl border bg-white p-4 shadow-sm" title={help}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p>{comparison !== undefined && <p className="mt-1 text-xs text-muted-foreground">{comparison == null ? "No prior baseline" : `${comparison >= 0 ? "+" : ""}${comparison}% vs prior period`}</p>}</div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-muted-foreground">{title}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{children}</div></section>; }

export function GrowthKpiDashboard({ data }: { data: GrowthDashboard }) {
  return <div className="space-y-7">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Growth dashboard</h1><p className="text-sm text-muted-foreground">DB-derived workspace funnel. Updated {new Date(data.generatedAt).toLocaleString()}</p></div><nav aria-label="Date range" className="flex rounded-lg border bg-white p-1">{ranges.map(range => <a key={range} href={`/admin/dashboard?range=${range}`} className={`rounded-md px-3 py-1.5 text-sm ${data.range === range ? "bg-[#6647F0] text-white" : "text-muted-foreground"}`}>{range}</a>)}</nav></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Card label="Signups" value={data.signups} comparison={comparePercent(data.signups, data.previous.signups)} help="Users created inside selected range"/><Card label="Activated workspaces" value={data.activated} comparison={comparePercent(data.activated, data.previous.activated)} help="Client + project + task, invoice, time entry, or portal visit"/><Card label="Paid accounts" value={data.paidAccounts} comparison={comparePercent(data.paidAccounts, data.previous.paidAccounts)} help="Distinct workspaces with completed plan payment"/><Card label="MRR" value={money(data.mrr)} comparison={comparePercent(data.mrr, data.previous.mrr)} help="Completed plan payments; annual plans divided by 12"/><Card label="ARR" value={money(data.arr)} help="MRR multiplied by 12"/><Card label="Churn" value="Not tracked yet" help="Requires entitlement history"/></div>
    <div className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Executive funnel</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{[["Signups", data.signups], ["Activated", data.activated], ["Paid", data.paidAccounts]].map(([label, value], i) => <div key={String(label)} className="rounded-lg bg-slate-50 p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p>{i > 0 && <p className="text-xs text-muted-foreground">{data.signups ? `${Math.round((Number(value) / data.signups) * 1000) / 10}% of signups` : "No signups"}</p>}</div>)}</div></div>
    <Section title="Acquisition"><Card label="Visitors" value="Not tracked yet" help={data.unavailable.visitors}/><Card label="Referrals" value="Not tracked yet" help={data.unavailable.referrals}/><Card label="CAC" value="Not tracked yet" help={data.unavailable.cac}/><Card label="Completed payments" value={data.completedPayments} help="Completed payment records"/></Section>
    <Section title="Activation"><Card label="Activated workspaces" value={data.activated} help="Client + project + meaningful activity"/><Card label="Activation rate" value={data.signups ? `${Math.round(data.activated / data.signups * 1000) / 10}%` : "—"} help="Activated workspaces divided by signups"/></Section>
    <Section title="Engagement"><Card label="Active workspaces" value={data.activeWorkspaces} help="Workspaces with meaningful activity in range"/><Card label="Active users" value={data.activeUsers} help="Workspace members in active workspaces"/><Card label="Projects" value={data.projects} help="Projects created in range"/><Card label="Tasks" value={data.tasks} help="Tasks created in range"/><Card label="Time tracking adoption" value={data.timeTrackingWorkspaces} help="Workspaces with time entries in range"/><Card label="Portal usage" value={data.portalWorkspaces} help="Workspaces with portal visits in range"/></Section>
    <Section title="Monetization"><Card label="ARPU" value={money(data.arpu)} help="MRR divided by paid accounts"/><Card label="MRR" value={money(data.mrr)} help="Monthly recurring equivalent"/><Card label="ARR" value={money(data.arr)} help="MRR × 12"/></Section>
    <Section title="Retention"><Card label="Retained paid accounts" value="Not tracked yet" help="Requires entitlement history"/><Card label="Churn" value="Not tracked yet" help="Requires entitlement history"/><Card label="Reactivation" value="Not tracked yet" help="Requires payment history transitions"/></Section>
    <Section title="Growth"><Card label="Net paid-account growth" value="Not tracked yet" help="Requires paid account state transitions"/><Card label="MRR growth" value={comparePercent(data.mrr, data.previous.mrr) == null ? "Not tracked yet" : `${comparePercent(data.mrr, data.previous.mrr)}%`} help="Period-over-period MRR change"/></Section>
  </div>;
}

export default GrowthKpiDashboard;
