"use client";

import { useMemo, useState } from "react";
import { CalendarClock, ChevronDown, MoreHorizontal, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Popover, PopoverAnchor, PopoverContent } from "@/components/ui/popover";
import { useT } from "@/lib/i18n-client";
import { isStaleServerActionError, staleServerActionMessage } from "@/lib/client-errors";
import { createRecurringInvoiceRule, deleteRecurringInvoiceRule, generateRecurringInvoiceNow, updateRecurringInvoiceRule } from "@/lib/actions/recurring-invoices";
import { renderRecurringInvoiceNumber } from "@/lib/recurring-invoice-number";
import { useAppTransition } from "@/lib/transition-provider";
import { formatMoney } from "@/lib/utils";

type Line={description:string;quantity:string;unitPrice:string};
export type RecurringInvoiceRuleView={id:string;clientId:string;projectId:string|null;frequency:"monthly"|"quarterly"|"yearly";startDate:string;endDate:string|null;nextRunDate:string;isActive:boolean;currency:string;numberPattern:string;lastSequence:number;notes:string|null;terms:string|null;discount?:string;chargeType?:"none"|"tax"|"admin";chargeRate?:string;dueDays?:number;lines:Array<{description:string;quantity:number;unitPrice:number}>};
type Props={rules:RecurringInvoiceRuleView[];clients:Array<{id:string;name:string}>;projects:Array<{id:string;clientId:string;name:string}>;canWrite:boolean;defaultCurrency:string};
type Form={clientId:string;projectId:string;frequency:RecurringInvoiceRuleView["frequency"];startDate:string;endDate:string;currency:"IDR"|"USD"|"EUR"|"GBP"|"SGD";numberPattern:string;notes:string;terms:string;discount:string;chargeType:"none"|"tax"|"admin";chargeRate:string;dueDays:string};
const today=()=>new Date().toISOString().slice(0,10);
const currency=(value:string):Form["currency"]=>["IDR","USD","EUR","GBP","SGD"].includes(value)?value as Form["currency"]:"IDR";

export function RecurringInvoiceManager({rules,clients,projects,canWrite,defaultCurrency}:Props){
 const {t,lang}=useT(); const {refresh}=useAppTransition();
 const blank=():Form=>({clientId:"",projectId:"",frequency:"monthly",startDate:today(),endDate:"",currency:currency(defaultCurrency),numberPattern:"INV-{YYYY}-{SEQ}",notes:"",terms:"",discount:"0",chargeType:"none",chargeRate:"0",dueDays:"14"});
 const [form,setForm]=useState(blank); const [lines,setLines]=useState<Line[]>([{description:"",quantity:"1",unitPrice:"0"}]); const [open,setOpen]=useState(false); const [pending,setPending]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [deleteId,setDeleteId]=useState<string|null>(null); const [clientSearchOpen,setClientSearchOpen]=useState(false); const [projectSearchOpen,setProjectSearchOpen]=useState(false); const [clientSearch,setClientSearch]=useState(""); const [projectSearch,setProjectSearch]=useState(""); const [menuId,setMenuId]=useState<string|null>(null);
 const set=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
 const selectedClient=clients.find(x=>x.id===form.clientId); const selectedProject=projects.find(x=>x.id===form.projectId);
 const filteredClients=clients.filter(x=>x.name.toLowerCase().includes(clientSearch.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
 const filteredProjects=projects.filter(x=>x.clientId===form.clientId&&x.name.toLowerCase().includes(projectSearch.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
 const patternValid=useMemo(()=>{try{renderRecurringInvoiceNumber(form.numberPattern,new Date().getFullYear(),1);return true}catch{return false}},[form.numberPattern]);
 const subtotal=lines.reduce((sum,x)=>sum+(Number(x.quantity)||0)*(Number(x.unitPrice)||0),0); const discount=Math.min(Number(form.discount)||0,subtotal); const charge=form.chargeType==="none"?0:(subtotal-discount)*(Number(form.chargeRate)||0)/100; const total=subtotal-discount+charge;
 const money=(n:number)=>formatMoney(n,form.currency);
 function create(){setEditingId(null);setForm(blank());setLines([{description:"",quantity:"1",unitPrice:"0"}]);setOpen(true)}
 function edit(rule:RecurringInvoiceRuleView){setEditingId(rule.id);setForm({clientId:rule.clientId,projectId:rule.projectId??"",frequency:rule.frequency,startDate:rule.nextRunDate,endDate:rule.endDate??"",currency:currency(rule.currency),numberPattern:rule.numberPattern,notes:rule.notes??"",terms:rule.terms??"",discount:rule.discount??"0",chargeType:rule.chargeType??"none",chargeRate:rule.chargeRate??"0",dueDays:String(rule.dueDays??14)});setLines(rule.lines.map(x=>({...x,quantity:String(x.quantity),unitPrice:String(x.unitPrice)})));setOpen(true)}
 function handleError(error:unknown,fallback:string){if(isStaleServerActionError(error)){toast.info(staleServerActionMessage(lang));window.location.reload();return}toast.error(error instanceof Error?error.message:fallback)}
 async function submit(e:React.FormEvent){e.preventDefault();setPending(true);try{const payload={...form,projectId:form.projectId||null,endDate:form.endDate||null,...(editingId?{nextRunDate:form.startDate}:{}),discount:Number(form.discount),chargeRate:Number(form.chargeRate),dueDays:Number(form.dueDays),lines:lines.map(x=>({description:x.description,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice)}))};if(editingId)await updateRecurringInvoiceRule(editingId,payload);else await createRecurringInvoiceRule(payload);toast.success(editingId?t("Invoice berulang diperbarui","Recurring invoice updated"):t("Invoice berulang dibuat","Recurring invoice created"));setOpen(false);refresh()}catch(e){handleError(e,t("Gagal menyimpan","Failed to save"))}finally{setPending(false)}}
 async function generate(id:string){setPending(true);try{const result=await generateRecurringInvoiceNow(id);toast.success(result?t("Draft invoice dibuat","Draft invoice generated"):t("Jadwal belum jatuh tempo","Schedule is not due yet"));refresh()}catch(e){handleError(e,t("Gagal membuat draft","Failed to generate draft"))}finally{setPending(false)}}
 async function toggle(rule:RecurringInvoiceRuleView){setPending(true);try{await updateRecurringInvoiceRule(rule.id,{isActive:!rule.isActive});refresh()}catch(e){handleError(e,t("Gagal memperbarui","Failed to update"))}finally{setPending(false)}}
 async function remove(ruleId:string){setPending(true);try{await deleteRecurringInvoiceRule(ruleId);toast.success(t("Invoice berulang dihapus","Recurring invoice deleted"));setDeleteId(null);refresh()}catch(e){handleError(e,t("Gagal menghapus","Failed to delete"))}finally{setPending(false)}}
 const picker=(kind:"client"|"project")=>{const isClient=kind==="client",isOpen=isClient?clientSearchOpen:projectSearchOpen,setOpenState=isClient?setClientSearchOpen:setProjectSearchOpen,query=isClient?clientSearch:projectSearch,setQuery=isClient?setClientSearch:setProjectSearch,items=isClient?filteredClients:filteredProjects,selected=isClient?selectedClient:selectedProject,disabled=!isClient&&!form.clientId;return <Popover open={isOpen} onOpenChange={setOpenState}><PopoverAnchor asChild><div className="relative"><Input role="combobox" disabled={disabled} value={isOpen?query:selected?.name??""} placeholder={disabled?t("Pilih klien dulu","Select client first"):isClient?t("Cari klien","Search client"):t("Cari proyek","Search project")} onClick={()=>setOpenState(true)} onFocus={()=>setOpenState(true)} onChange={e=>{setQuery(e.target.value);setOpenState(true)}} className="pr-9"/><ChevronDown className={`pointer-events-none absolute right-3 top-3 h-4 w-4 text-muted-foreground ${isOpen?"rotate-180":""}`}/></div></PopoverAnchor><PopoverContent align="start" className="w-[var(--radix-popover-trigger-width)] p-1"><div className="max-h-60 overflow-y-auto">{!isClient&&<button type="button" className="min-h-10 w-full rounded px-3 text-left text-sm hover:bg-muted" onClick={()=>{set("projectId","");setOpenState(false)}}>{t("Tanpa proyek","No project")}</button>}{items.map(item=><button key={item.id} type="button" className="min-h-10 w-full rounded px-3 text-left text-sm hover:bg-muted" onClick={()=>{if(isClient){set("clientId",item.id);set("projectId","");setProjectSearch("")}else set("projectId",item.id);setQuery("");setOpenState(false)}}>{item.name}</button>)}</div></PopoverContent></Popover>};
 return <section id="recurring-invoices" className="rounded-xl border bg-card"><div className="flex flex-col gap-3 border-b px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 className="font-semibold">{t("Invoice Berulang","Recurring Invoices")}</h2><p className="text-sm text-muted-foreground">{t("Draft dibuat otomatis sesuai jadwal untuk direview sebelum dikirim.","Drafts are created on schedule for review before sending.")}</p></div>{canWrite&&clients.length?<Button size="sm" onClick={create}><Plus className="mr-1 h-4 w-4"/>{t("Invoice berulang baru","New recurring invoice")}</Button>:null}</div>
 {rules.length===0?<div className="flex min-h-48 flex-col items-center justify-center p-8 text-center"><CalendarClock className="mb-3 h-5 w-5 text-muted-foreground"/><p className="font-medium">{t("Belum ada invoice berulang","No recurring invoices yet")}</p></div>:<div className="divide-y">{rules.map(rule=>{const amount=rule.lines.reduce((s,x)=>s+x.quantity*x.unitPrice,0);return <div key={rule.id} className="grid gap-3 px-4 py-3 sm:px-5 lg:grid-cols-[minmax(0,1fr)_100px_130px_130px_auto] lg:items-center"><div><p className="truncate font-medium">{clients.find(x=>x.id===rule.clientId)?.name}</p><p className="truncate text-xs text-muted-foreground">{projects.find(x=>x.id===rule.projectId)?.name||t("Tanpa proyek","No project")}</p></div><p className="text-sm capitalize">{rule.frequency}</p><p className="text-sm font-medium tabular-nums">{formatMoney(amount,rule.currency)}</p><p className="text-sm tabular-nums">{rule.nextRunDate}</p><div className="flex items-center justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>edit(rule)}>{t("Edit","Edit")}</Button><Popover open={menuId===rule.id} onOpenChange={x=>setMenuId(x?rule.id:null)}><PopoverAnchor asChild><Button size="icon" variant="ghost"><MoreHorizontal className="h-4 w-4"/></Button></PopoverAnchor><PopoverContent align="end" className="w-48 p-1"><button className="min-h-9 w-full rounded px-3 text-left text-sm hover:bg-muted" onClick={()=>generate(rule.id)}>{t("Generate jika jatuh tempo","Generate if due")}</button><button className="min-h-9 w-full rounded px-3 text-left text-sm hover:bg-muted" onClick={()=>toggle(rule)}>{rule.isActive?t("Jeda","Pause"):t("Aktifkan","Activate")}</button><button className="min-h-9 w-full rounded px-3 text-left text-sm text-destructive hover:bg-muted" onClick={()=>setDeleteId(rule.id)}>{t("Hapus","Delete")}</button></PopoverContent></Popover></div></div>})}</div>}
 <Dialog open={open} onOpenChange={x=>!pending&&setOpen(x)}><DialogContent className="max-h-[90vh] overflow-hidden p-0 sm:max-w-2xl"><form onSubmit={submit} className="flex max-h-[90vh] flex-col"><DialogHeader className="border-b px-6 py-5 text-left"><DialogTitle>{editingId?t("Edit invoice berulang","Edit recurring invoice"):t("Invoice berulang baru","New recurring invoice")}</DialogTitle><DialogDescription>{t("Atur penerima, jadwal, item, dan total draft.","Set recipient, schedule, items, and draft total.")}</DialogDescription></DialogHeader><div className="grid min-h-0 flex-1 gap-4 overflow-y-auto px-6 py-5 sm:grid-cols-2"><div className="space-y-1"><Label>{t("Klien","Client")} *</Label>{picker("client")}</div><div className="space-y-1"><Label>{t("Proyek (opsional)","Project (optional)")}</Label>{picker("project")}</div><div className="space-y-1"><Label>{t("Frekuensi","Frequency")}</Label><Select value={form.frequency} onValueChange={x=>set("frequency",x)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["monthly","quarterly","yearly"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>{t("Mata uang","Currency")}</Label><Select value={form.currency} onValueChange={x=>set("currency",x)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["IDR","USD","EUR","GBP","SGD"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>{editingId?t("Tanggal invoice berikutnya","Next invoice date"):t("Mulai","Start")}</Label><Input type="date" value={form.startDate} onChange={e=>set("startDate",e.target.value)}/></div><div className="space-y-1"><Label>{t("Selesai (opsional)","End (optional)")}</Label><Input type="date" value={form.endDate} onChange={e=>set("endDate",e.target.value)}/></div><div className="space-y-1"><Label>{t("Jatuh tempo (hari)","Due in days")}</Label><Input type="number" min="0" max="365" value={form.dueDays} onChange={e=>set("dueDays",e.target.value)}/></div>
 <div className="space-y-2 sm:col-span-2"><div className="flex items-center justify-between"><Label>{t("Item tagihan","Invoice items")}</Label><Button type="button" size="sm" variant="outline" onClick={()=>setLines(x=>[...x,{description:"",quantity:"1",unitPrice:"0"}])}>+ {t("Tambah item","Add item")}</Button></div>{lines.map((line,i)=><div key={i} className="grid grid-cols-[minmax(0,1fr)_70px_110px_36px] gap-2"><Input placeholder={t("Deskripsi","Description")} value={line.description} onChange={e=>setLines(x=>x.map((r,j)=>j===i?{...r,description:e.target.value}:r))}/><Input type="number" min="0.01" value={line.quantity} onChange={e=>setLines(x=>x.map((r,j)=>j===i?{...r,quantity:e.target.value}:r))}/><Input type="number" min="0" value={line.unitPrice} onChange={e=>setLines(x=>x.map((r,j)=>j===i?{...r,unitPrice:e.target.value}:r))}/><Button type="button" size="icon" variant="ghost" disabled={lines.length===1} onClick={()=>setLines(x=>x.filter((_,j)=>j!==i))}><Trash2 className="h-4 w-4"/></Button></div>)}</div>
 <div className="space-y-1"><Label>{t("Diskon","Discount")}</Label><Input type="number" min="0" value={form.discount} onChange={e=>set("discount",e.target.value)}/></div><div className="space-y-1"><Label>{t("Tambahan","Charge")}</Label><Select value={form.chargeType} onValueChange={x=>set("chargeType",x)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{t("Tidak ada","None")}</SelectItem><SelectItem value="tax">{t("Pajak","Tax")}</SelectItem><SelectItem value="admin">{t("Biaya admin","Admin fee")}</SelectItem></SelectContent></Select>{form.chargeType!=="none"&&<Input type="number" min="0" max="100" value={form.chargeRate} onChange={e=>set("chargeRate",e.target.value)} aria-label={t("Tarif tambahan (%)","Charge rate (%)")}/>}</div><div className="rounded-lg bg-muted/40 p-3 text-sm sm:col-span-2"><div className="flex justify-between"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between"><span>{t("Diskon","Discount")}</span><span>-{money(discount)}</span></div><div className="mt-2 flex justify-between border-t pt-2 font-bold"><span>Total</span><span>{money(total)}</span></div></div>
 <details className="rounded-lg border p-3 sm:col-span-2"><summary className="cursor-pointer text-sm font-medium">{t("Pengaturan lanjutan","Advanced settings")}</summary><div className="mt-4 space-y-4"><Label>{t("Pola nomor","Number pattern")}</Label><Input value={form.numberPattern} aria-invalid={!patternValid} onChange={e=>set("numberPattern",e.target.value)}/>{!patternValid&&<p className="text-xs text-destructive">{t("Pola nomor tidak valid","Invalid number pattern")}</p>}<Textarea placeholder={t("Catatan","Notes")} value={form.notes} onChange={e=>set("notes",e.target.value)}/><Textarea placeholder={t("Syarat","Terms")} value={form.terms} onChange={e=>set("terms",e.target.value)}/></div></details></div><DialogFooter className="shrink-0 border-t px-6 py-4"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>{t("Batal","Cancel")}</Button><Button disabled={pending||!form.clientId||!patternValid||lines.some(x=>!x.description||Number(x.quantity)<=0)}>{t("Simpan invoice berulang","Save recurring invoice")}</Button></DialogFooter></form></DialogContent></Dialog>
 <Dialog open={!!deleteId} onOpenChange={x=>!x&&setDeleteId(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>{t("Hapus invoice berulang?","Delete recurring invoice?")}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{t("Draft lama tidak ikut dihapus.","Existing drafts will not be deleted.")}</p><DialogFooter><Button variant="outline" onClick={()=>setDeleteId(null)}>{t("Batal","Cancel")}</Button><Button variant="destructive" onClick={()=>deleteId&&remove(deleteId)}>{t("Hapus","Delete")}</Button></DialogFooter></DialogContent></Dialog></section>
}
