"use client";
import { useState } from "react";
import { Loader2, Trash2, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { formatAssistantRelativeTime, getAssistantCopy, type AssistantLang } from "@/lib/ai/ui-copy";
export type AssistantConversation={id:string;title:string;updatedAt:string;messageCount:number};
export function AssistantHistory({open,onClose,lang,items,activeId,onLoad,onDelete}:{open:boolean;onClose:()=>void;lang:AssistantLang;items:AssistantConversation[];activeId:string|null;onLoad:(id:string)=>void;onDelete:(id:string)=>Promise<void>}){
 const [deleteTarget,setDeleteTarget]=useState<AssistantConversation|null>(null);const [deletingId,setDeletingId]=useState<string|null>(null);const c=getAssistantCopy(lang);if(!open)return null;
 async function remove(){if(!deleteTarget)return;setDeletingId(deleteTarget.id);await onDelete(deleteTarget.id);setDeletingId(null);setDeleteTarget(null)}
 return <div className="fixed inset-0 z-50 bg-black/30" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside role="dialog" aria-modal="true" aria-label={c.historyTitle} className="absolute inset-y-0 right-0 flex w-full max-w-sm flex-col bg-white shadow-xl"><header className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">{c.historyTitle}</h2><button onClick={onClose} className="min-h-11 min-w-11 rounded-lg"><X className="mx-auto h-4 w-4"/></button></header><div className="flex-1 overflow-y-auto p-3">{items.length===0?<p className="p-8 text-center text-sm text-slate-500">{c.noHistory}</p>:<ul className="space-y-1">{items.map(item=><li key={item.id} className={cn("flex rounded-xl border",item.id===activeId&&"border-purple-300 bg-purple-50")}><button onClick={()=>{onLoad(item.id);onClose()}} className="min-w-0 flex-1 p-3 text-left"><span className="block truncate text-sm font-medium">{item.title}</span><span className="text-xs text-slate-500">{formatAssistantRelativeTime(item.updatedAt,lang)}</span></button><button disabled={deletingId===item.id} onClick={()=>setDeleteTarget(item)} className="min-h-11 min-w-11 text-slate-400 hover:text-red-600" aria-label={`${c.delete}: ${item.title}`}>{deletingId===item.id?<Loader2 className="mx-auto h-4 w-4 animate-spin"/>:<Trash2 className="mx-auto h-4 w-4"/>}</button></li>)}</ul>}</div></aside>{deleteTarget&&<div role="alertdialog" aria-modal="true" className="absolute inset-0 flex items-center justify-center bg-black/20 p-4"><div className="w-full max-w-sm rounded-2xl bg-white p-5 shadow-xl"><h3 className="font-semibold">{c.deleteTitle}</h3><p className="mt-2 text-sm text-slate-600">{c.deleteBody}</p><div className="mt-5 flex justify-end gap-2"><button disabled={Boolean(deletingId)} onClick={()=>setDeleteTarget(null)} className="min-h-11 rounded-lg border px-4">{c.cancel}</button><button disabled={Boolean(deletingId)} onClick={remove} className="min-h-11 rounded-lg bg-red-600 px-4 text-white">{deletingId?<Loader2 className="h-4 w-4 animate-spin"/>:c.delete}</button></div></div></div>}</div>
}
