"use client";
import { useState, type KeyboardEvent, type RefObject } from "react";
import { Send, Sparkles, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { assistantCategoryLabels, assistantQuickActions, localizeAssistantAction, primaryAssistantActions } from "@/lib/ai/quick-actions";
import { getAssistantCopy, type AssistantLang } from "@/lib/ai/ui-copy";

export function AssistantEmptyState({ lang, input, setInput, send, busy, stop, inputRef, onKeyDown, openHistory }: { lang: AssistantLang; input: string; setInput: (v:string)=>void; send:(v:string)=>void; busy:boolean; stop:()=>void; inputRef:RefObject<HTMLTextAreaElement|null>; onKeyDown:(e:KeyboardEvent<HTMLTextAreaElement>)=>void; openHistory:()=>void }) {
  const [allOpen,setAllOpen]=useState(false); const copy=getAssistantCopy(lang);
  return <div className="mx-auto flex min-h-full w-full max-w-3xl flex-col px-4 py-5 md:py-10">
    <header className="flex items-center justify-between"><div><h1 className="text-lg font-semibold text-slate-900">{copy.title}</h1><p className="text-xs text-slate-500">{copy.subtitle}</p></div><button onClick={openHistory} className="min-h-11 rounded-lg px-3 text-sm text-slate-600 hover:bg-slate-100">{copy.history}</button></header>
    <main className="mx-auto my-auto w-full max-w-2xl py-6"><div className="text-center"><Sparkles className="mx-auto h-9 w-9 text-[var(--cu-purple)]"/><h2 className="mt-3 text-xl font-semibold text-slate-900 md:text-2xl">{copy.greeting}</h2></div>
      <form onSubmit={e=>{e.preventDefault();send(input)}} className="mt-5 rounded-2xl border bg-white p-2 shadow-sm focus-within:border-[var(--cu-purple)]"><label className="sr-only" htmlFor="assistant-empty-input">{copy.placeholder}</label><textarea id="assistant-empty-input" ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={onKeyDown} rows={2} placeholder={copy.placeholder} className="max-h-32 min-h-14 w-full resize-none bg-transparent px-3 py-2 text-sm outline-none"/><div className="flex justify-end"><Button type={busy?"button":"submit"} onClick={busy?stop:undefined} disabled={!busy&&!input.trim()} className="h-11 rounded-xl bg-[var(--cu-purple)] text-white">{busy?<XCircle className="h-4 w-4"/>:<><Send className="mr-2 h-4 w-4"/>{copy.send}</>}</Button></div></form>
      <section className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">{copy.startHere}</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{primaryAssistantActions.map(action=>{const {label,prompt}=localizeAssistantAction(action,lang);return <button key={action.id} onClick={()=>{setInput(prompt);inputRef.current?.focus()}} className="min-h-11 rounded-xl border px-3 py-2 text-left text-sm font-medium hover:border-[var(--cu-purple)]">{label}</button>})}</div><button onClick={()=>setAllOpen(true)} className="mt-3 min-h-11 text-sm font-medium text-[var(--cu-purple)]">{copy.allHelp}</button></section>
      <section className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b>{copy.capabilityReadTitle}:</b> {copy.capabilityRead}<br/><b>{copy.capabilityActTitle}:</b> {copy.capabilityAct}</section>
    </main>
    {allOpen&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-end bg-black/30 sm:items-center sm:justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)setAllOpen(false)}}><div className="max-h-[85dvh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 sm:max-w-lg sm:rounded-2xl"><div className="flex justify-between"><h2 className="font-semibold">{copy.allHelp}</h2><button onClick={()=>setAllOpen(false)}>{copy.close}</button></div>{Object.entries(assistantCategoryLabels).map(([category,title])=><section key={category} className="mt-4"><h3 className="text-xs font-semibold uppercase text-slate-500">{title[lang]}</h3><div className="mt-1 grid gap-1">{assistantQuickActions.filter(a=>a.category===category).map(a=>{const v=localizeAssistantAction(a,lang);return <button key={a.id} onClick={()=>{setInput(v.prompt);setAllOpen(false);inputRef.current?.focus()}} className="min-h-11 rounded-lg px-3 text-left text-sm hover:bg-slate-50">{v.label}</button>})}</div></section>)}</div></div>}
  </div>;
}
