"use client";

import { useState } from "react";
import { Clock, History, Loader2, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { deleteGeneration } from "@/lib/actions/prompts";
import { launchPromptCatalog, mapLegacyPromptType, type PromptTypeId } from "@/lib/prompts/catalog";
import { parsePromptResult, type PromptGenerationResult } from "@/lib/prompts/build-prompt";
import { useT } from "@/lib/i18n-client";
import { toast } from "sonner";

export type PromptHistoryItem = { id: string; input: unknown; generatedOutput: string | null; costUsd: string | null; createdAt: Date | string };
function inputRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function resolveType(input: Record<string, unknown>): PromptTypeId | null { const direct = input.promptType; if (typeof direct === "string" && launchPromptCatalog.some((item) => item.id === direct)) return direct as PromptTypeId; return typeof input.mode === "string" ? mapLegacyPromptType(input.mode) : null; }

export function PromptHistoryDrawer({ items: initialItems, onSelect }: { items: PromptHistoryItem[]; onSelect(result: PromptGenerationResult): void }) {
  const { t, lang } = useT();
  const [items, setItems] = useState(initialItems); const [deleteId, setDeleteId] = useState<string | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [open, setOpen] = useState(false);
  async function remove() { if (!deleteId) return; setDeletingId(deleteId); try { await deleteGeneration(deleteId); setItems((list) => list.filter((item) => item.id !== deleteId)); toast.success(t("Riwayat dihapus", "History deleted")); setDeleteId(null); } catch (error) { toast.error(error instanceof Error ? error.message : t("Gagal menghapus riwayat", "Failed to delete history")); } finally { setDeletingId(null); } }
  return <><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="outline"><History className="h-4 w-4"/>{t("Riwayat", "History")}</Button></SheetTrigger><SheetContent className="w-full overflow-y-auto sm:max-w-md"><SheetHeader><SheetTitle>{t("Riwayat Prompt", "Prompt History")}</SheetTitle><SheetDescription>{t("Buka kembali materi yang pernah dibuat.", "Reopen material you created before.")}</SheetDescription></SheetHeader><div className="mt-6 space-y-2 px-4 pb-6">{items.length === 0 && <p className="py-12 text-center text-sm text-muted-foreground">{t("Belum ada riwayat.", "No history yet.")}</p>}{items.map((item) => { const input = inputRecord(item.input); const typeId = resolveType(input); const type = typeId ? launchPromptCatalog.find((entry) => entry.id === typeId) : null; const title = String(input.campaign || input.product || t("Prompt lama", "Legacy prompt")); return <div key={item.id} className="group rounded-xl border p-3"><button className="w-full text-left" onClick={() => { if (typeId) onSelect(parsePromptResult(item.generatedOutput || "", typeId).result); setOpen(false); }}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-sm font-semibold">{type ? (lang === "en" && type.nameEn ? type.nameEn : type.name) : t("Prompt lama", "Legacy prompt")}</p><p className="truncate text-sm text-muted-foreground">{title}</p></div>{item.costUsd && Number(item.costUsd) > 0 && <span className="text-[11px] text-muted-foreground">${Number(item.costUsd).toFixed(4)}</span>}</div><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Clock className="h-3 w-3"/>{new Date(item.createdAt).toLocaleString(lang === "en" ? "en-US" : "id-ID", { dateStyle: "medium", timeStyle: "short" })}</p><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{item.generatedOutput || t("Tidak ada output", "No output")}</p></button><Button variant="ghost" size="sm" className="mt-2 text-destructive" disabled={deletingId === item.id} onClick={() => setDeleteId(item.id)}>{deletingId === item.id ? <Loader2 className="h-3.5 w-3.5 animate-spin"/> : <Trash2 className="h-3.5 w-3.5"/>}{t("Hapus", "Delete")}</Button></div>; })}</div></SheetContent></Sheet>
  <Dialog open={Boolean(deleteId)} onOpenChange={(next: boolean) => !next && setDeleteId(null)}><DialogContent><DialogHeader><DialogTitle>{t("Hapus riwayat ini?", "Delete this history?")}</DialogTitle><DialogDescription>{t("Materi yang dihapus tidak dapat dipulihkan.", "Deleted material cannot be recovered.")}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteId(null)}>{t("Batal", "Cancel")}</Button><Button variant="destructive" onClick={remove}>{t("Hapus", "Delete")}</Button></DialogFooter></DialogContent></Dialog></>;
}
