"use client";

import { useMemo, useState } from "react";
import { Check, ChevronRight, Loader2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { generateVisualPrompt } from "@/lib/actions/visual-prompts";
import { launchPromptCatalog, type PromptCategory, type PromptOptionValue, type PromptTypeId } from "@/lib/prompts/catalog";
import { parsePromptResult, type PromptGenerationResult } from "@/lib/prompts/build-prompt";
import { PromptResult } from "./prompt-result";
import { PromptHistoryDrawer, type PromptHistoryItem } from "./prompt-history-drawer";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const categories: { id: PromptCategory; label: string }[] = [{ id: "social-media", label: "Social Media" }, { id: "ads-promotion", label: "Iklan & Promosi" }, { id: "product", label: "Produk" }, { id: "video", label: "Video" }, { id: "brand-copy", label: "Brand & Copy" }];
type FormState = { brand: string; campaign: string; goal: string; audience: string; offer: string; tone: string; style: string; platform: string; ratio: string; colorPalette: string; notes: string; options: Record<string, PromptOptionValue> };
const empty: FormState = { brand: "", campaign: "", goal: "", audience: "", offer: "", tone: "", style: "", platform: "", ratio: "", colorPalette: "", notes: "", options: {} };

export function PromptStudio({ generations, usage }: { generations: PromptHistoryItem[]; usage: { totalInputTokens: number; totalOutputTokens: number; totalCost: number; monthlyCap: number; totalGenerations: number; generationLimit: number | null } }) {
  const [category, setCategory] = useState<PromptCategory>("social-media"); const [typeId, setTypeId] = useState<PromptTypeId>("instagram-feed"); const [form, setForm] = useState(empty); const [result, setResult] = useState<PromptGenerationResult | null>(null); const [loading, setLoading] = useState(false);
  const [pendingType, setPendingType] = useState<PromptTypeId | null>(null);
  const selected = launchPromptCatalog.find((item) => item.id === typeId)!; const types = launchPromptCatalog.filter((item) => item.category === category);
  const valid = useMemo(() => Boolean(form.brand.trim() && form.campaign.trim() && form.goal.trim() && form.audience.trim() && selected.fields.filter((field) => field.required).every((field) => form.options[field.key] !== undefined && form.options[field.key] !== "")), [form, selected]);
  function patchField(key: keyof Omit<FormState, "options">, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  function applyType(next: PromptTypeId) { const item = launchPromptCatalog.find((entry) => entry.id === next)!; setCategory(item.category); setTypeId(next); setForm((current) => ({ ...current, options: { ...item.defaults } })); setResult(null); setPendingType(null); }
  function chooseType(next: PromptTypeId) { if (result && next !== typeId) { setPendingType(next); return; } applyType(next); }
  function chooseCategory(next: PromptCategory) { const first = launchPromptCatalog.find((item) => item.category === next)!; if (result) { setPendingType(first.id); return; } applyType(first.id); }
  async function generate() { if (!valid || loading) return; setLoading(true); try { const response = await generateVisualPrompt({ promptType: typeId, ...form }); const next = parsePromptResult(response.generation.generatedOutput || "", typeId).result; setResult(next); toast.success("Materi selesai dibuat"); } catch (error) { toast.error(error instanceof Error ? error.message : "Materi gagal dibuat"); } finally { setLoading(false); } }
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="app-page-title">Prompt Studio</h1><p className="mt-1 text-sm text-muted-foreground">Buat materi campaign dari brief sederhana.</p></div><div className="flex items-center gap-3"><span className="text-xs text-muted-foreground">Generate {usage.totalGenerations}/{usage.generationLimit ?? "Unlimited"}</span><PromptHistoryDrawer items={generations} onSelect={setResult}/></div></div>
    <section className="rounded-2xl border bg-white p-3 sm:p-5"><div className="grid gap-3 md:hidden"><div className="space-y-1.5"><Label htmlFor="prompt-category-mobile">Kategori</Label><select id="prompt-category-mobile" aria-label="Pilih kategori prompt" value={category} onChange={(event) => chooseCategory(event.target.value as PromptCategory)} className="h-11 w-full rounded-md border bg-background px-3 text-sm font-medium">{categories.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div className="space-y-1.5"><Label htmlFor="prompt-type-mobile">Jenis konten</Label><select id="prompt-type-mobile" aria-label="Pilih jenis konten" value={typeId} onChange={(event) => chooseType(event.target.value as PromptTypeId)} className="h-11 w-full rounded-md border bg-background px-3 text-sm font-medium">{types.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><p className="text-xs leading-5 text-muted-foreground">{selected.description}</p></div></div><div className="hidden gap-2 overflow-x-auto pb-2 md:flex">{categories.map((item) => <button key={item.id} onClick={() => chooseCategory(item.id)} className={cn("min-h-11 shrink-0 rounded-lg px-4 text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary", category === item.id ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground hover:text-foreground")}>{item.label}</button>)}</div><div className="mt-3 hidden gap-2 md:grid md:grid-cols-2 lg:grid-cols-4">{types.map((item) => <button key={item.id} onClick={() => chooseType(item.id)} className={cn("min-h-[76px] rounded-xl border p-3 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary", typeId === item.id ? "border-primary bg-primary/5 ring-1 ring-primary" : "hover:bg-muted/40")}><div className="flex items-center justify-between"><span className="text-sm font-semibold">{item.name}</span>{typeId === item.id ? <Check className="h-4 w-4 text-primary"/> : <ChevronRight className="h-4 w-4 text-muted-foreground"/>}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.description}</p></button>)}</div></section>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(360px,430px)_minmax(0,1fr)]"><section id="prompt-brief" className="rounded-2xl border bg-slate-50/70 p-4 sm:p-5"><div className="mb-3 sm:mb-4"><p className="font-semibold">Brief {selected.name}</p><p className="text-xs text-muted-foreground">Isi empat informasi utama, lalu detail khusus bila diperlukan.</p></div><div className="space-y-3 sm:space-y-4">{[["brand","Brand","Contoh: Cubiqlo"],["campaign","Product / campaign","Contoh: Aplikasi pengelolaan klien untuk freelancer"],["goal","Goal","Contoh: Mendorong pendaftaran akun gratis"],["audience","Audience","Contoh: Freelancer Indonesia yang kewalahan mengelola banyak klien"]].map(([key,label,placeholder]) => <div className="space-y-1.5" key={key}><Label htmlFor={key}>{label}</Label><Input id={key} value={form[key as keyof FormState] as string} placeholder={placeholder} onChange={(event) => patchField(key as keyof Omit<FormState,"options">, event.target.value)}/></div>)}
      {selected.fields.map((field) => <div className="space-y-1.5" key={field.key}><Label htmlFor={`option-${field.key}`}>{field.label}{field.required ? " *" : ""}</Label>{field.type === "select" ? <Select value={String(form.options[field.key] ?? "")} onValueChange={(value) => setForm((current) => ({ ...current, options: { ...current.options, [field.key]: field.key.endsWith("Count") ? Number(value) : value } }))}><SelectTrigger id={`option-${field.key}`}><SelectValue placeholder="Pilih opsi"/></SelectTrigger><SelectContent>{field.options?.map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select> : field.type === "textarea" ? <Textarea id={`option-${field.key}`} value={String(form.options[field.key] ?? "")} onChange={(event) => setForm((current) => ({ ...current, options: { ...current.options, [field.key]: event.target.value } }))}/> : <Input id={`option-${field.key}`} type={field.type} min={field.min} max={field.max} value={String(form.options[field.key] ?? "")} onChange={(event) => setForm((current) => ({ ...current, options: { ...current.options, [field.key]: field.type === "number" ? Number(event.target.value) : event.target.value } }))}/>}</div>)}
      <details className="rounded-xl border bg-white p-3"><summary className="cursor-pointer text-sm font-medium">Advanced options</summary><div className="mt-4 space-y-3">{([...["offer","tone","style","platform","ratio","colorPalette","notes"]] as Array<keyof Omit<FormState,"options">>).map((key) => <div className="space-y-1.5" key={key}><Label htmlFor={key}>{key === "colorPalette" ? "Color palette" : key === "notes" ? "Catatan tambahan" : key[0].toUpperCase() + key.slice(1)}</Label>{key === "notes" ? <Textarea id={key} value={form[key]} onChange={(e) => patchField(key,e.target.value)}/> : <Input id={key} value={form[key]} onChange={(e) => patchField(key,e.target.value)}/>}</div>)}</div></details>
      <Button className="h-11 w-full" disabled={!valid || loading} onClick={generate}>{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Sparkles className="mr-2 h-4 w-4"/>}{loading ? "Menyusun materi…" : "Generate Materi"}</Button></div></section><PromptResult result={result} loading={loading} onEdit={() => document.getElementById("prompt-brief")?.scrollIntoView({ behavior: "smooth" })} onRegenerate={generate}/></div>
      <Dialog open={Boolean(pendingType)} onOpenChange={(open) => !open && setPendingType(null)}><DialogContent><DialogHeader><DialogTitle>Ganti jenis konten?</DialogTitle><DialogDescription>Hasil yang sedang tampil akan ditutup. Brief utama tetap tersimpan.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setPendingType(null)}>Batal</Button><Button onClick={() => pendingType && applyType(pendingType)}>Ganti jenis</Button></DialogFooter></DialogContent></Dialog>
    </div>;
}
