"use client";

import { useState } from "react";
import { Clock, History, Loader2, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { deleteGeneration } from "@/lib/actions/prompts";
import { launchPromptCatalog, mapLegacyPromptType, type PromptTypeId } from "@/lib/prompts/catalog";
import { parsePromptResult, type PromptGenerationResult } from "@/lib/prompts/build-prompt";
import { toast } from "sonner";

export type PromptHistoryItem = { id: string; input: unknown; generatedOutput: string | null; costUsd: string | null; createdAt: Date | string };
function inputRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function resolveType(input: Record<string, unknown>): PromptTypeId | null { const direct = input.promptType; if (typeof direct === "string" && launchPromptCatalog.some((item) => item.id === direct)) return direct as PromptTypeId; return typeof input.mode === "string" ? mapLegacyPromptType(input.mode) : null; }

export function PromptHistoryDrawer({ items: initialItems, onSelect }: { items: PromptHistoryItem[]; onSelect(result: PromptGenerationResult): void }) {
  const [items, setItems] = useState(initialItems); const [deleteId, setDeleteId] = useState<string | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [open, setOpen] = useState(false);
  async function remove() { if (!deleteId) return; setDeletingId(deleteId); try { await deleteGeneration(deleteId); setItems((list) => list.filter((item) => item.id !== deleteId)); toast.success("Riwayat dihapus"); setDeleteId(null); } catch (error) { toast.error(error instanceof Error ? error.message : "Gagal menghapus riwayat"); } finally { setDeletingId(null); } }
  return <><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="outline"><History className="mr-2 h-4 w-4"/>Riwayat</Button></SheetTrigger><SheetContent className="w-full overflow-y-auto sm:max-w-md"><SheetHeader><SheetTitle>Riwayat Prompt</SheetTitle><SheetDescription>Buka kembali materi yang pernah dibuat.</SheetDescription></SheetHeader><div className="mt-6 space-y-2 px-4 pb-6">{items.length === 0 && <p className="py-12 text-center text-sm text-muted-foreground">Belum ada riwayat.</p>}{items.map((item) => { const input = inputRecord(item.input); const typeId = resolveType(input); const type = typeId ? launchPromptCatalog.find((entry) => entry.id === typeId) : null; const title = String(input.campaign || input.product || "Prompt lama"); return <div key={item.id} className="group rounded-xl border p-3"><button className="w-full text-left" onClick={() => { if (typeId) onSelect(parsePromptResult(item.generatedOutput || "", typeId).result); setOpen(false); }}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-sm font-semibold">{type?.name || "Prompt lama"}</p><p className="truncate text-sm text-muted-foreground">{title}</p></div>{item.costUsd && Number(item.costUsd) > 0 && <span className="text-[11px] text-muted-foreground">${Number(item.costUsd).toFixed(4)}</span>}</div><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Clock className="h-3 w-3"/>{new Date(item.createdAt).toLocaleString("id-ID", { dateStyle: "medium", timeStyle: "short" })}</p><p className="mt-2 line-clamp-2 text-xs text-muted-foreground">{item.generatedOutput || "Tidak ada output"}</p></button><Button variant="ghost" size="sm" className="mt-2 text-destructive" disabled={deletingId === item.id} onClick={() => setDeleteId(item.id)}>{deletingId === item.id ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin"/> : <Trash2 className="mr-1.5 h-3.5 w-3.5"/>}Hapus</Button></div>; })}</div></SheetContent></Sheet>
  <Dialog open={Boolean(deleteId)} onOpenChange={(next: boolean) => !next && setDeleteId(null)}><DialogContent><DialogHeader><DialogTitle>Hapus riwayat ini?</DialogTitle><DialogDescription>Materi yang dihapus tidak dapat dipulihkan.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteId(null)}>Batal</Button><Button variant="destructive" onClick={remove}>Hapus</Button></DialogFooter></DialogContent></Dialog></>;
}
