"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createProject, updateProject } from "@/lib/actions/projects";
import { Button } from "@/components/ui/button";
import { DialogClose } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type BillingModel="fixed_price"|"hourly"|"retainer";
type Defaults={id?:string;name?:string;description?:string;clientId?:string;status?:string;billingModel?:BillingModel;billingType?:string;currency?:string;rate?:string;budget?:string;retainerFee?:string;retainerIncludedMinutes?:number;retainerResetDay?:number;retainerOveragePolicy?:"none"|"warn"|"bill";retainerOverageRate?:string;startDate?:string;finishDate?:string;dueDate?:string;clientVisible?:boolean;selectedPackageId?:string|null;serviceIds?:string[];[legacy:string]:unknown};
export function ProjectForm({mode,clientId,clients=[],defaultValues,onSuccess}:{mode:"create"|"edit";clientId?:string;clients?:Array<{id:string;name:string}>;defaultValues?:Defaults;onSuccess?:()=>void}){
 const router=useRouter(); const [loading,setLoading]=useState(false);
 const fallback:BillingModel=defaultValues?.billingType==="hours"?"hourly":"fixed_price";
 const [form,setForm]=useState({name:defaultValues?.name??"",description:defaultValues?.description??"",clientId:defaultValues?.clientId??clientId??"",status:defaultValues?.status??"active",billingModel:defaultValues?.billingModel??fallback,currency:defaultValues?.currency??"IDR",rate:defaultValues?.rate??"",budget:defaultValues?.budget??"",retainerFee:defaultValues?.retainerFee??"",retainerIncludedMinutes:String(defaultValues?.retainerIncludedMinutes??""),retainerResetDay:String(defaultValues?.retainerResetDay??1),retainerOveragePolicy:defaultValues?.retainerOveragePolicy??"none",retainerOverageRate:defaultValues?.retainerOverageRate??"",startDate:defaultValues?.startDate??"",finishDate:defaultValues?.finishDate??"",dueDate:defaultValues?.dueDate??"",clientVisible:defaultValues?.clientVisible??false});
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);try{const data={...form,billingModel:form.billingModel as BillingModel,rate:form.rate?Number(form.rate):undefined,budget:form.budget?Number(form.budget):undefined,retainerFee:form.retainerFee?Number(form.retainerFee):undefined,retainerIncludedMinutes:form.retainerIncludedMinutes?Number(form.retainerIncludedMinutes):undefined,retainerResetDay:form.retainerResetDay?Number(form.retainerResetDay):undefined,retainerOveragePolicy:form.retainerOveragePolicy as "none"|"warn"|"bill",retainerOverageRate:form.retainerOverageRate?Number(form.retainerOverageRate):undefined,status:form.status as "draft"|"active"|"on_hold"|"completed"|"cancelled"|"archived",clientVisible:form.clientVisible};if(mode==="create")await createProject(data);else if(defaultValues?.id)await updateProject(defaultValues.id,data);toast.success(mode==="create"?"Project dibuat":"Project diperbarui");onSuccess?.();router.refresh()}catch(e){toast.error(e instanceof Error?e.message:"Gagal menyimpan")}finally{setLoading(false)}}
 const field=(label:string,key:keyof typeof form,type="text")=><div className="space-y-2"><Label>{label}</Label><Input type={type} value={String(form[key]??"")} onChange={e=>setForm(p=>({...p,[key]:e.target.value}))}/></div>;
 return <form onSubmit={submit} className="space-y-4">{field("Nama Project *","name")}{field("Deskripsi","description")}{!clientId&&<div className="space-y-2"><Label>Klien *</Label><Select value={form.clientId} onValueChange={v=>setForm(p=>({...p,clientId:v}))}><SelectTrigger><SelectValue placeholder="Pilih klien"/></SelectTrigger><SelectContent>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>}<div className="space-y-2"><Label>Model tagihan</Label><Select value={form.billingModel} onValueChange={v=>setForm(p=>({...p,billingModel:v as BillingModel}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="fixed_price">Harga Tetap</SelectItem><SelectItem value="hourly">Per Jam</SelectItem><SelectItem value="retainer">Retainer</SelectItem></SelectContent></Select></div>{form.billingModel==="fixed_price"&&field(`Nilai Project (${form.currency})`,`budget`,`number`)}{form.billingModel==="hourly"&&field(`Rate per Jam (${form.currency})`,`rate`,`number`)}{form.billingModel==="retainer"&&<div className="grid gap-3 sm:grid-cols-2">{field("Biaya Retainer","retainerFee","number")}{field("Menit termasuk","retainerIncludedMinutes","number")}{field("Tanggal reset (1–28)","retainerResetDay","number")}<div className="space-y-2"><Label>Kebijakan overage</Label><Select value={form.retainerOveragePolicy} onValueChange={v=>setForm(p=>({...p,retainerOveragePolicy:v as typeof p.retainerOveragePolicy}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Tidak ada</SelectItem><SelectItem value="warn">Peringatkan</SelectItem><SelectItem value="bill">Tagihkan</SelectItem></SelectContent></Select></div>{form.retainerOveragePolicy==="bill"&&field("Rate overage","retainerOverageRate","number")}</div>}<div className="grid grid-cols-2 gap-2"><DialogClose asChild><Button type="button" variant="outline">Batal</Button></DialogClose><Button disabled={loading}>{loading?"Menyimpan...":"Simpan"}</Button></div></form>
}
